package v1_20

type All struct {
	IoK8sApimachineryPkgApisMetaV1ServerAddressByClientCIDR                                 IoK8sApimachineryPkgApisMetaV1ServerAddressByClientCIDR
	IoK8sAPIRbacV1beta1RoleBinding                                                          IoK8sAPIRbacV1beta1RoleBinding
	IoK8sApimachineryPkgApisMetaV1ObjectMeta                                                IoK8sApimachineryPkgApisMetaV1ObjectMeta
	IoK8sAPIRbacV1beta1RoleRef                                                              IoK8sAPIRbacV1beta1RoleRef
	IoK8sAPIRbacV1beta1Subject                                                              IoK8sAPIRbacV1beta1Subject
	IoK8sAPICoreV1ContainerState                                                            IoK8sAPICoreV1ContainerState
	IoK8sAPICoreV1ContainerStateRunning                                                     IoK8sAPICoreV1ContainerStateRunning
	IoK8sAPICoreV1ContainerStateTerminated                                                  IoK8sAPICoreV1ContainerStateTerminated
	IoK8sAPICoreV1ContainerStateWaiting                                                     IoK8sAPICoreV1ContainerStateWaiting
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinition               IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinition
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionSpec           IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionSpec
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionStatus         IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionStatus
	IoK8sAPICoreV1AzureFileVolumeSource                                                     IoK8sAPICoreV1AzureFileVolumeSource
	IoK8sAPIAutoscalingV1HorizontalPodAutoscalerList                                        IoK8sAPIAutoscalingV1HorizontalPodAutoscalerList
	IoK8sAPIAutoscalingV1HorizontalPodAutoscaler                                            IoK8sAPIAutoscalingV1HorizontalPodAutoscaler
	IoK8sApimachineryPkgApisMetaV1ListMeta                                                  IoK8sApimachineryPkgApisMetaV1ListMeta
	IoK8sAPICoreV1ResourceRequirements                                                      IoK8sAPICoreV1ResourceRequirements
	IoK8sApimachineryPkgAPIResourceQuantity                                                 IoK8sApimachineryPkgAPIResourceQuantity
	IoK8sAPIAuthorizationV1beta1ResourceAttributes                                          IoK8sAPIAuthorizationV1beta1ResourceAttributes
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps                   IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaProps
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrBool             IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrBool
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSON                              IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSON
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrStringArray      IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrStringArray
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1ExternalDocumentation             IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1ExternalDocumentation
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrArray            IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1JSONSchemaPropsOrArray
	IoK8sAPINetworkingV1beta1IngressStatus                                                  IoK8sAPINetworkingV1beta1IngressStatus
	IoK8sAPICoreV1LoadBalancerStatus                                                        IoK8sAPICoreV1LoadBalancerStatus
	IoK8sAPICoreV1NodeAffinity                                                              IoK8sAPICoreV1NodeAffinity
	IoK8sAPICoreV1PreferredSchedulingTerm                                                   IoK8sAPICoreV1PreferredSchedulingTerm
	IoK8sAPICoreV1NodeSelector                                                              IoK8sAPICoreV1NodeSelector
	IoK8sApimachineryPkgRuntimeRawExtension                                                 IoK8sApimachineryPkgRuntimeRawExtension
	IoK8sAPICoreV1PersistentVolumeSpec                                                      IoK8sAPICoreV1PersistentVolumeSpec
	IoK8sAPICoreV1AWSElasticBlockStoreVolumeSource                                          IoK8sAPICoreV1AWSElasticBlockStoreVolumeSource
	IoK8sAPICoreV1AzureDiskVolumeSource                                                     IoK8sAPICoreV1AzureDiskVolumeSource
	IoK8sAPICoreV1AzureFilePersistentVolumeSource                                           IoK8sAPICoreV1AzureFilePersistentVolumeSource
	IoK8sAPICoreV1CephFSPersistentVolumeSource                                              IoK8sAPICoreV1CephFSPersistentVolumeSource
	IoK8sAPICoreV1CinderPersistentVolumeSource                                              IoK8sAPICoreV1CinderPersistentVolumeSource
	IoK8sAPICoreV1ObjectReference                                                           IoK8sAPICoreV1ObjectReference
	IoK8sAPICoreV1CSIPersistentVolumeSource                                                 IoK8sAPICoreV1CSIPersistentVolumeSource
	IoK8sAPICoreV1FCVolumeSource                                                            IoK8sAPICoreV1FCVolumeSource
	IoK8sAPICoreV1FlexPersistentVolumeSource                                                IoK8sAPICoreV1FlexPersistentVolumeSource
	IoK8sAPICoreV1FlockerVolumeSource                                                       IoK8sAPICoreV1FlockerVolumeSource
	IoK8sAPICoreV1GCEPersistentDiskVolumeSource                                             IoK8sAPICoreV1GCEPersistentDiskVolumeSource
	IoK8sAPICoreV1GlusterfsPersistentVolumeSource                                           IoK8sAPICoreV1GlusterfsPersistentVolumeSource
	IoK8sAPICoreV1HostPathVolumeSource                                                      IoK8sAPICoreV1HostPathVolumeSource
	IoK8sAPICoreV1ISCSIPersistentVolumeSource                                               IoK8sAPICoreV1ISCSIPersistentVolumeSource
	IoK8sAPICoreV1LocalVolumeSource                                                         IoK8sAPICoreV1LocalVolumeSource
	IoK8sAPICoreV1NFSVolumeSource                                                           IoK8sAPICoreV1NFSVolumeSource
	IoK8sAPICoreV1VolumeNodeAffinity                                                        IoK8sAPICoreV1VolumeNodeAffinity
	IoK8sAPICoreV1PhotonPersistentDiskVolumeSource                                          IoK8sAPICoreV1PhotonPersistentDiskVolumeSource
	IoK8sAPICoreV1PortworxVolumeSource                                                      IoK8sAPICoreV1PortworxVolumeSource
	IoK8sAPICoreV1QuobyteVolumeSource                                                       IoK8sAPICoreV1QuobyteVolumeSource
	IoK8sAPICoreV1RBDPersistentVolumeSource                                                 IoK8sAPICoreV1RBDPersistentVolumeSource
	IoK8sAPICoreV1ScaleIOPersistentVolumeSource                                             IoK8sAPICoreV1ScaleIOPersistentVolumeSource
	IoK8sAPICoreV1StorageOSPersistentVolumeSource                                           IoK8sAPICoreV1StorageOSPersistentVolumeSource
	IoK8sAPICoreV1VsphereVirtualDiskVolumeSource                                            IoK8sAPICoreV1VsphereVirtualDiskVolumeSource
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1ServiceReference                       IoK8sApiextensionsApiserverPkgApisApiextensionsV1ServiceReference
	IoK8sAPIApiserverinternalV1alpha1StorageVersionSpec                                     IoK8sAPIApiserverinternalV1alpha1StorageVersionSpec
	IoK8sAPICoreV1Node                                                                      IoK8sAPICoreV1Node
	IoK8sAPICoreV1NodeSpec                                                                  IoK8sAPICoreV1NodeSpec
	IoK8sAPICoreV1NodeStatus                                                                IoK8sAPICoreV1NodeStatus
	IoK8sAPICoreV1Handler                                                                   IoK8sAPICoreV1Handler
	IoK8sAPICoreV1ExecAction                                                                IoK8sAPICoreV1ExecAction
	IoK8sAPICoreV1HTTPGetAction                                                             IoK8sAPICoreV1HTTPGetAction
	IoK8sAPICoreV1TCPSocketAction                                                           IoK8sAPICoreV1TCPSocketAction
	IoK8sAPIAutoscalingV2beta2ObjectMetricSource                                            IoK8sAPIAutoscalingV2beta2ObjectMetricSource
	IoK8sAPIAutoscalingV2beta2CrossVersionObjectReference                                   IoK8sAPIAutoscalingV2beta2CrossVersionObjectReference
	IoK8sAPIAutoscalingV2beta2MetricIdentifier                                              IoK8sAPIAutoscalingV2beta2MetricIdentifier
	IoK8sAPIAutoscalingV2beta2MetricTarget                                                  IoK8sAPIAutoscalingV2beta2MetricTarget
	IoK8sAPIPolicyV1beta1PodDisruptionBudget                                                IoK8sAPIPolicyV1beta1PodDisruptionBudget
	IoK8sAPIPolicyV1beta1PodDisruptionBudgetSpec                                            IoK8sAPIPolicyV1beta1PodDisruptionBudgetSpec
	IoK8sAPIPolicyV1beta1PodDisruptionBudgetStatus                                          IoK8sAPIPolicyV1beta1PodDisruptionBudgetStatus
	IoK8sAPINetworkingV1IngressClassSpec                                                    IoK8sAPINetworkingV1IngressClassSpec
	IoK8sAPICoreV1TypedLocalObjectReference                                                 IoK8sAPICoreV1TypedLocalObjectReference
	IoK8sAPICoreV1ServicePort                                                               IoK8sAPICoreV1ServicePort
	IoK8sApimachineryPkgUtilIntstrIntOrString                                               IoK8sApimachineryPkgUtilIntstrIntOrString
	IoK8sAPIApiserverinternalV1alpha1StorageVersionCondition                                IoK8sAPIApiserverinternalV1alpha1StorageVersionCondition
	IoK8sApimachineryPkgApisMetaV1Time                                                      IoK8sApimachineryPkgApisMetaV1Time
	IoK8sAPICoreV1SecretList                                                                IoK8sAPICoreV1SecretList
	IoK8sAPICoreV1Secret                                                                    IoK8sAPICoreV1Secret
	IoK8sAPICoreV1ResourceQuota                                                             IoK8sAPICoreV1ResourceQuota
	IoK8sAPICoreV1ResourceQuotaSpec                                                         IoK8sAPICoreV1ResourceQuotaSpec
	IoK8sAPICoreV1ResourceQuotaStatus                                                       IoK8sAPICoreV1ResourceQuotaStatus
	IoK8sAPIStorageV1CSIDriverList                                                          IoK8sAPIStorageV1CSIDriverList
	IoK8sAPIStorageV1CSIDriver                                                              IoK8sAPIStorageV1CSIDriver
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresources        IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresources
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScale    IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceScale
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceStatus   IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceSubresourceStatus
	IoK8sAPIRbacV1alpha1RoleBindingList                                                     IoK8sAPIRbacV1alpha1RoleBindingList
	IoK8sAPIRbacV1alpha1RoleBinding                                                         IoK8sAPIRbacV1alpha1RoleBinding
	IoK8sApimachineryPkgApisMetaV1OwnerReference                                            IoK8sApimachineryPkgApisMetaV1OwnerReference
	IoK8sAPICoreV1PersistentVolumeClaimSpec                                                 IoK8sAPICoreV1PersistentVolumeClaimSpec
	IoK8sApimachineryPkgApisMetaV1LabelSelector                                             IoK8sApimachineryPkgApisMetaV1LabelSelector
	IoK8sAPIAutoscalingV2beta1ExternalMetricStatus                                          IoK8sAPIAutoscalingV2beta1ExternalMetricStatus
	IoK8sAPICoreV1NamespaceStatus                                                           IoK8sAPICoreV1NamespaceStatus
	IoK8sAPICoreV1NamespaceCondition                                                        IoK8sAPICoreV1NamespaceCondition
	IoK8sAPICoreV1PodTemplateList                                                           IoK8sAPICoreV1PodTemplateList
	IoK8sAPICoreV1PodTemplate                                                               IoK8sAPICoreV1PodTemplate
	IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceStatus                        IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceStatus
	IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceCondition                     IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceCondition
	IoK8sAPIApiserverinternalV1alpha1StorageVersionStatus                                   IoK8sAPIApiserverinternalV1alpha1StorageVersionStatus
	IoK8sAPIApiserverinternalV1alpha1ServerStorageVersion                                   IoK8sAPIApiserverinternalV1alpha1ServerStorageVersion
	IoK8sAPIStorageV1alpha1VolumeAttachmentList                                             IoK8sAPIStorageV1alpha1VolumeAttachmentList
	IoK8sAPIStorageV1alpha1VolumeAttachment                                                 IoK8sAPIStorageV1alpha1VolumeAttachment
	IoK8sAPINetworkingV1beta1Ingress                                                        IoK8sAPINetworkingV1beta1Ingress
	IoK8sAPINetworkingV1beta1IngressSpec                                                    IoK8sAPINetworkingV1beta1IngressSpec
	IoK8sAPIAppsV1RollingUpdateStatefulSetStrategy                                          IoK8sAPIAppsV1RollingUpdateStatefulSetStrategy
	IoK8sAPIRbacV1beta1RoleBindingList                                                      IoK8sAPIRbacV1beta1RoleBindingList
	IoK8sAPINetworkingV1NetworkPolicyPort                                                   IoK8sAPINetworkingV1NetworkPolicyPort
	IoK8sAPIAuthorizationV1SubjectAccessReviewSpec                                          IoK8sAPIAuthorizationV1SubjectAccessReviewSpec
	IoK8sAPIAuthorizationV1NonResourceAttributes                                            IoK8sAPIAuthorizationV1NonResourceAttributes
	IoK8sAPIAuthorizationV1ResourceAttributes                                               IoK8sAPIAuthorizationV1ResourceAttributes
	IoK8sAPIFlowcontrolV1beta1GroupSubject                                                  IoK8sAPIFlowcontrolV1beta1GroupSubject
	IoK8sAPIAuthorizationV1beta1SubjectAccessReviewSpec                                     IoK8sAPIAuthorizationV1beta1SubjectAccessReviewSpec
	IoK8sAPIAuthorizationV1beta1NonResourceAttributes                                       IoK8sAPIAuthorizationV1beta1NonResourceAttributes
	IoK8sKubeAggregatorPkgApisApiregistrationV1beta1ServiceReference                        IoK8sKubeAggregatorPkgApisApiregistrationV1beta1ServiceReference
	IoK8sAPICoreV1ReplicationControllerStatus                                               IoK8sAPICoreV1ReplicationControllerStatus
	IoK8sAPICoreV1ReplicationControllerCondition                                            IoK8sAPICoreV1ReplicationControllerCondition
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceStatus        IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceStatus
	IoK8sAPIAutoscalingV2beta1HorizontalPodAutoscalerCondition                              IoK8sAPIAutoscalingV2beta1HorizontalPodAutoscalerCondition
	IoK8sAPIAppsV1ReplicaSetStatus                                                          IoK8sAPIAppsV1ReplicaSetStatus
	IoK8sAPIAppsV1ReplicaSetCondition                                                       IoK8sAPIAppsV1ReplicaSetCondition
	IoK8sAPICertificatesV1beta1CertificateSigningRequestStatus                              IoK8sAPICertificatesV1beta1CertificateSigningRequestStatus
	IoK8sAPICertificatesV1beta1CertificateSigningRequestCondition                           IoK8sAPICertificatesV1beta1CertificateSigningRequestCondition
	IoK8sAPICoreV1NodeAddress                                                               IoK8sAPICoreV1NodeAddress
	IoK8sAPICoreV1PodDNSConfig                                                              IoK8sAPICoreV1PodDNSConfig
	IoK8sAPICoreV1PodDNSConfigOption                                                        IoK8sAPICoreV1PodDNSConfigOption
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionList      IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionList
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition          IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinition
	IoK8sAPICoreV1EventSource                                                               IoK8sAPICoreV1EventSource
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceConversion               IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceConversion
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1WebhookConversion                      IoK8sApiextensionsApiserverPkgApisApiextensionsV1WebhookConversion
	IoK8sAPIAdmissionregistrationV1beta1MutatingWebhookConfigurationList                    IoK8sAPIAdmissionregistrationV1beta1MutatingWebhookConfigurationList
	IoK8sAPIAdmissionregistrationV1beta1MutatingWebhookConfiguration                        IoK8sAPIAdmissionregistrationV1beta1MutatingWebhookConfiguration
	IoK8sAPIExtensionsV1beta1Ingress                                                        IoK8sAPIExtensionsV1beta1Ingress
	IoK8sAPIExtensionsV1beta1IngressSpec                                                    IoK8sAPIExtensionsV1beta1IngressSpec
	IoK8sAPIExtensionsV1beta1IngressStatus                                                  IoK8sAPIExtensionsV1beta1IngressStatus
	IoK8sAPIAutoscalingV2beta2HorizontalPodAutoscalerList                                   IoK8sAPIAutoscalingV2beta2HorizontalPodAutoscalerList
	IoK8sAPIAutoscalingV2beta2HorizontalPodAutoscaler                                       IoK8sAPIAutoscalingV2beta2HorizontalPodAutoscaler
	IoK8sAPIFlowcontrolV1beta1PriorityLevelConfiguration                                    IoK8sAPIFlowcontrolV1beta1PriorityLevelConfiguration
	IoK8sAPIFlowcontrolV1beta1PriorityLevelConfigurationSpec                                IoK8sAPIFlowcontrolV1beta1PriorityLevelConfigurationSpec
	IoK8sAPIFlowcontrolV1beta1PriorityLevelConfigurationStatus                              IoK8sAPIFlowcontrolV1beta1PriorityLevelConfigurationStatus
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionList           IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionList
	IoK8sAPIAppsV1StatefulSetStatus                                                         IoK8sAPIAppsV1StatefulSetStatus
	IoK8sAPIAppsV1StatefulSetCondition                                                      IoK8sAPIAppsV1StatefulSetCondition
	IoK8sAPIBatchV2alpha1CronJobStatus                                                      IoK8sAPIBatchV2alpha1CronJobStatus
	IoK8sAPIAutoscalingV2beta2ExternalMetricSource                                          IoK8sAPIAutoscalingV2beta2ExternalMetricSource
	IoK8sAPICoreV1NodeConfigSource                                                          IoK8sAPICoreV1NodeConfigSource
	IoK8sAPICoreV1ConfigMapNodeConfigSource                                                 IoK8sAPICoreV1ConfigMapNodeConfigSource
	IoK8sApimachineryPkgApisMetaV1APIGroupList                                              IoK8sApimachineryPkgApisMetaV1APIGroupList
	IoK8sApimachineryPkgApisMetaV1APIGroup                                                  IoK8sApimachineryPkgApisMetaV1APIGroup
	IoK8sAPICoreV1SecretReference                                                           IoK8sAPICoreV1SecretReference
	IoK8sAPICoreV1ServiceAccountList                                                        IoK8sAPICoreV1ServiceAccountList
	IoK8sAPICoreV1ServiceAccount                                                            IoK8sAPICoreV1ServiceAccount
	IoK8sAPICoreV1WeightedPodAffinityTerm                                                   IoK8sAPICoreV1WeightedPodAffinityTerm
	IoK8sAPICoreV1PodAffinityTerm                                                           IoK8sAPICoreV1PodAffinityTerm
	IoK8sAPIAutoscalingV2beta1ContainerResourceMetricStatus                                 IoK8sAPIAutoscalingV2beta1ContainerResourceMetricStatus
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1WebhookClientConfig                    IoK8sApiextensionsApiserverPkgApisApiextensionsV1WebhookClientConfig
	IoK8sAPINodeV1beta1RuntimeClassList                                                     IoK8sAPINodeV1beta1RuntimeClassList
	IoK8sAPINodeV1beta1RuntimeClass                                                         IoK8sAPINodeV1beta1RuntimeClass
	IoK8sAPICoreV1Pod                                                                       IoK8sAPICoreV1Pod
	IoK8sAPICoreV1PodSpec                                                                   IoK8sAPICoreV1PodSpec
	IoK8sAPICoreV1PodStatus                                                                 IoK8sAPICoreV1PodStatus
	IoK8sAPIAuthenticationV1TokenRequestStatus                                              IoK8sAPIAuthenticationV1TokenRequestStatus
	IoK8sAPIEventsV1Event                                                                   IoK8sAPIEventsV1Event
	IoK8sApimachineryPkgApisMetaV1MicroTime                                                 IoK8sApimachineryPkgApisMetaV1MicroTime
	IoK8sAPIEventsV1EventSeries                                                             IoK8sAPIEventsV1EventSeries
	IoK8sAPICoreV1SecretKeySelector                                                         IoK8sAPICoreV1SecretKeySelector
	IoK8sAPIFlowcontrolV1alpha1PriorityLevelConfigurationReference                          IoK8sAPIFlowcontrolV1alpha1PriorityLevelConfigurationReference
	IoK8sAPIStorageV1beta1VolumeAttachmentStatus                                            IoK8sAPIStorageV1beta1VolumeAttachmentStatus
	IoK8sAPIStorageV1beta1VolumeError                                                       IoK8sAPIStorageV1beta1VolumeError
	IoK8sApimachineryPkgApisMetaV1GroupVersionForDiscovery                                  IoK8sApimachineryPkgApisMetaV1GroupVersionForDiscovery
	IoK8sAPINetworkingV1NetworkPolicyList                                                   IoK8sAPINetworkingV1NetworkPolicyList
	IoK8sAPINetworkingV1NetworkPolicy                                                       IoK8sAPINetworkingV1NetworkPolicy
	IoK8sAPICoreV1Container                                                                 IoK8sAPICoreV1Container
	IoK8sAPICoreV1EnvVar                                                                    IoK8sAPICoreV1EnvVar
	IoK8sAPICoreV1EnvFromSource                                                             IoK8sAPICoreV1EnvFromSource
	IoK8sAPICoreV1Lifecycle                                                                 IoK8sAPICoreV1Lifecycle
	IoK8sAPICoreV1Probe                                                                     IoK8sAPICoreV1Probe
	IoK8sAPICoreV1ContainerPort                                                             IoK8sAPICoreV1ContainerPort
	IoK8sAPICoreV1SecurityContext                                                           IoK8sAPICoreV1SecurityContext
	IoK8sAPICoreV1VolumeDevice                                                              IoK8sAPICoreV1VolumeDevice
	IoK8sAPICoreV1VolumeMount                                                               IoK8sAPICoreV1VolumeMount
	IoK8sAPICoreV1Volume                                                                    IoK8sAPICoreV1Volume
	IoK8sAPICoreV1CephFSVolumeSource                                                        IoK8sAPICoreV1CephFSVolumeSource
	IoK8sAPICoreV1CinderVolumeSource                                                        IoK8sAPICoreV1CinderVolumeSource
	IoK8sAPICoreV1ConfigMapVolumeSource                                                     IoK8sAPICoreV1ConfigMapVolumeSource
	IoK8sAPICoreV1CSIVolumeSource                                                           IoK8sAPICoreV1CSIVolumeSource
	IoK8sAPICoreV1DownwardAPIVolumeSource                                                   IoK8sAPICoreV1DownwardAPIVolumeSource
	IoK8sAPICoreV1EmptyDirVolumeSource                                                      IoK8sAPICoreV1EmptyDirVolumeSource
	IoK8sAPICoreV1EphemeralVolumeSource                                                     IoK8sAPICoreV1EphemeralVolumeSource
	IoK8sAPICoreV1FlexVolumeSource                                                          IoK8sAPICoreV1FlexVolumeSource
	IoK8sAPICoreV1GitRepoVolumeSource                                                       IoK8sAPICoreV1GitRepoVolumeSource
	IoK8sAPICoreV1GlusterfsVolumeSource                                                     IoK8sAPICoreV1GlusterfsVolumeSource
	IoK8sAPICoreV1ISCSIVolumeSource                                                         IoK8sAPICoreV1ISCSIVolumeSource
	IoK8sAPICoreV1PersistentVolumeClaimVolumeSource                                         IoK8sAPICoreV1PersistentVolumeClaimVolumeSource
	IoK8sAPICoreV1ProjectedVolumeSource                                                     IoK8sAPICoreV1ProjectedVolumeSource
	IoK8sAPICoreV1RBDVolumeSource                                                           IoK8sAPICoreV1RBDVolumeSource
	IoK8sAPICoreV1ScaleIOVolumeSource                                                       IoK8sAPICoreV1ScaleIOVolumeSource
	IoK8sAPICoreV1SecretVolumeSource                                                        IoK8sAPICoreV1SecretVolumeSource
	IoK8sAPICoreV1StorageOSVolumeSource                                                     IoK8sAPICoreV1StorageOSVolumeSource
	IoK8sAPISchedulingV1alpha1PriorityClass                                                 IoK8sAPISchedulingV1alpha1PriorityClass
	IoK8sAPIDiscoveryV1beta1EndpointSlice                                                   IoK8sAPIDiscoveryV1beta1EndpointSlice
	IoK8sAPIDiscoveryV1beta1Endpoint                                                        IoK8sAPIDiscoveryV1beta1Endpoint
	IoK8sAPIDiscoveryV1beta1EndpointPort                                                    IoK8sAPIDiscoveryV1beta1EndpointPort
	IoK8sAPINodeV1Overhead                                                                  IoK8sAPINodeV1Overhead
	IoK8sAPICoreV1TopologySelectorLabelRequirement                                          IoK8sAPICoreV1TopologySelectorLabelRequirement
	IoK8sAPIDiscoveryV1beta1EndpointConditions                                              IoK8sAPIDiscoveryV1beta1EndpointConditions
	IoK8sAPICoreV1KeyToPath                                                                 IoK8sAPICoreV1KeyToPath
	IoK8sAPIRbacV1ClusterRole                                                               IoK8sAPIRbacV1ClusterRole
	IoK8sAPIRbacV1AggregationRule                                                           IoK8sAPIRbacV1AggregationRule
	IoK8sAPIRbacV1PolicyRule                                                                IoK8sAPIRbacV1PolicyRule
	IoK8sAPINetworkingV1Ingress                                                             IoK8sAPINetworkingV1Ingress
	IoK8sAPINetworkingV1IngressSpec                                                         IoK8sAPINetworkingV1IngressSpec
	IoK8sAPINetworkingV1IngressStatus                                                       IoK8sAPINetworkingV1IngressStatus
	IoK8sAPIFlowcontrolV1alpha1LimitResponse                                                IoK8sAPIFlowcontrolV1alpha1LimitResponse
	IoK8sAPIFlowcontrolV1alpha1QueuingConfiguration                                         IoK8sAPIFlowcontrolV1alpha1QueuingConfiguration
	IoK8sAPINetworkingV1IngressBackend                                                      IoK8sAPINetworkingV1IngressBackend
	IoK8sAPINetworkingV1IngressRule                                                         IoK8sAPINetworkingV1IngressRule
	IoK8sAPINetworkingV1IngressTLS                                                          IoK8sAPINetworkingV1IngressTLS
	IoK8sAPICoreV1Toleration                                                                IoK8sAPICoreV1Toleration
	IoK8sAPIFlowcontrolV1alpha1FlowSchemaSpec                                               IoK8sAPIFlowcontrolV1alpha1FlowSchemaSpec
	IoK8sAPIFlowcontrolV1alpha1FlowDistinguisherMethod                                      IoK8sAPIFlowcontrolV1alpha1FlowDistinguisherMethod
	IoK8sAPIFlowcontrolV1alpha1PolicyRulesWithSubjects                                      IoK8sAPIFlowcontrolV1alpha1PolicyRulesWithSubjects
	IoK8sAPIRbacV1beta1ClusterRoleBinding                                                   IoK8sAPIRbacV1beta1ClusterRoleBinding
	IoK8sAPIStorageV1VolumeAttachment                                                       IoK8sAPIStorageV1VolumeAttachment
	IoK8sAPIStorageV1VolumeAttachmentSpec                                                   IoK8sAPIStorageV1VolumeAttachmentSpec
	IoK8sAPIStorageV1VolumeAttachmentStatus                                                 IoK8sAPIStorageV1VolumeAttachmentStatus
	IoK8sAPIAdmissionregistrationV1ValidatingWebhook                                        IoK8sAPIAdmissionregistrationV1ValidatingWebhook
	IoK8sAPIAdmissionregistrationV1WebhookClientConfig                                      IoK8sAPIAdmissionregistrationV1WebhookClientConfig
	IoK8sAPIAdmissionregistrationV1RuleWithOperations                                       IoK8sAPIAdmissionregistrationV1RuleWithOperations
	IoK8sAPICoreV1NodeConfigStatus                                                          IoK8sAPICoreV1NodeConfigStatus
	IoK8sAPICoreV1ScopeSelector                                                             IoK8sAPICoreV1ScopeSelector
	IoK8sAPIExtensionsV1beta1IngressTLS                                                     IoK8sAPIExtensionsV1beta1IngressTLS
	IoK8sAPIAppsV1DeploymentStrategy                                                        IoK8sAPIAppsV1DeploymentStrategy
	IoK8sAPIAppsV1RollingUpdateDeployment                                                   IoK8sAPIAppsV1RollingUpdateDeployment
	IoK8sAPIPolicyV1beta1AllowedHostPath                                                    IoK8sAPIPolicyV1beta1AllowedHostPath
	IoK8sAPIAuthenticationV1UserInfo                                                        IoK8sAPIAuthenticationV1UserInfo
	IoK8sAPIAuthorizationV1SubjectRulesReviewStatus                                         IoK8sAPIAuthorizationV1SubjectRulesReviewStatus
	IoK8sAPIAuthorizationV1NonResourceRule                                                  IoK8sAPIAuthorizationV1NonResourceRule
	IoK8sAPIAuthorizationV1ResourceRule                                                     IoK8sAPIAuthorizationV1ResourceRule
	IoK8sAPICoreV1PodList                                                                   IoK8sAPICoreV1PodList
	IoK8sAPISchedulingV1beta1PriorityClassList                                              IoK8sAPISchedulingV1beta1PriorityClassList
	IoK8sAPISchedulingV1beta1PriorityClass                                                  IoK8sAPISchedulingV1beta1PriorityClass
	IoK8sAPIAutoscalingV2beta1CrossVersionObjectReference                                   IoK8sAPIAutoscalingV2beta1CrossVersionObjectReference
	IoK8sAPIRbacV1RoleBindingList                                                           IoK8sAPIRbacV1RoleBindingList
	IoK8sAPIRbacV1RoleBinding                                                               IoK8sAPIRbacV1RoleBinding
	IoK8sAPIAppsV1StatefulSetUpdateStrategy                                                 IoK8sAPIAppsV1StatefulSetUpdateStrategy
	IoK8sAPICoreV1LoadBalancerIngress                                                       IoK8sAPICoreV1LoadBalancerIngress
	IoK8sAPICoreV1NodeSelectorTerm                                                          IoK8sAPICoreV1NodeSelectorTerm
	IoK8sAPICoreV1NodeSelectorRequirement                                                   IoK8sAPICoreV1NodeSelectorRequirement
	IoK8sAPIFlowcontrolV1alpha1PriorityLevelConfigurationStatus                             IoK8sAPIFlowcontrolV1alpha1PriorityLevelConfigurationStatus
	IoK8sAPIFlowcontrolV1alpha1PriorityLevelConfigurationCondition                          IoK8sAPIFlowcontrolV1alpha1PriorityLevelConfigurationCondition
	IoK8sAPIFlowcontrolV1beta1PolicyRulesWithSubjects                                       IoK8sAPIFlowcontrolV1beta1PolicyRulesWithSubjects
	IoK8sAPIFlowcontrolV1beta1NonResourcePolicyRule                                         IoK8sAPIFlowcontrolV1beta1NonResourcePolicyRule
	IoK8sAPIFlowcontrolV1beta1ResourcePolicyRule                                            IoK8sAPIFlowcontrolV1beta1ResourcePolicyRule
	IoK8sAPIFlowcontrolV1beta1Subject                                                       IoK8sAPIFlowcontrolV1beta1Subject
	IoK8sAPIBatchV1beta1JobTemplateSpec                                                     IoK8sAPIBatchV1beta1JobTemplateSpec
	IoK8sAPIBatchV1JobSpec                                                                  IoK8sAPIBatchV1JobSpec
	IoK8sAPINetworkingV1beta1IngressTLS                                                     IoK8sAPINetworkingV1beta1IngressTLS
	IoK8sAPIStorageV1beta1CSIDriver                                                         IoK8sAPIStorageV1beta1CSIDriver
	IoK8sAPIStorageV1beta1CSIDriverSpec                                                     IoK8sAPIStorageV1beta1CSIDriverSpec
	IoK8sAPIPolicyV1beta1RuntimeClassStrategyOptions                                        IoK8sAPIPolicyV1beta1RuntimeClassStrategyOptions
	IoK8sAPIAppsV1ReplicaSetList                                                            IoK8sAPIAppsV1ReplicaSetList
	IoK8sAPIAppsV1ReplicaSet                                                                IoK8sAPIAppsV1ReplicaSet
	IoK8sAPICoreV1EndpointAddress                                                           IoK8sAPICoreV1EndpointAddress
	IoK8sAPINodeV1alpha1Scheduling                                                          IoK8sAPINodeV1alpha1Scheduling
	IoK8sAPIRbacV1Role                                                                      IoK8sAPIRbacV1Role
	IoK8sAPIAdmissionregistrationV1beta1WebhookClientConfig                                 IoK8sAPIAdmissionregistrationV1beta1WebhookClientConfig
	IoK8sAPIAdmissionregistrationV1beta1ServiceReference                                    IoK8sAPIAdmissionregistrationV1beta1ServiceReference
	IoK8sAPIRbacV1ClusterRoleBinding                                                        IoK8sAPIRbacV1ClusterRoleBinding
	IoK8sAPIRbacV1RoleRef                                                                   IoK8sAPIRbacV1RoleRef
	IoK8sAPIRbacV1Subject                                                                   IoK8sAPIRbacV1Subject
	IoK8sAPICoreV1ContainerStatus                                                           IoK8sAPICoreV1ContainerStatus
	IoK8sApimachineryPkgApisMetaV1DeleteOptions                                             IoK8sApimachineryPkgApisMetaV1DeleteOptions
	IoK8sApimachineryPkgApisMetaV1Preconditions                                             IoK8sApimachineryPkgApisMetaV1Preconditions
	IoK8sAPIStorageV1beta1CSINodeList                                                       IoK8sAPIStorageV1beta1CSINodeList
	IoK8sAPIStorageV1beta1CSINode                                                           IoK8sAPIStorageV1beta1CSINode
	IoK8sAPICoreV1NodeCondition                                                             IoK8sAPICoreV1NodeCondition
	IoK8sAPIEventsV1beta1Event                                                              IoK8sAPIEventsV1beta1Event
	IoK8sAPIEventsV1beta1EventSeries                                                        IoK8sAPIEventsV1beta1EventSeries
	IoK8sAPIAuthorizationV1beta1SelfSubjectAccessReviewSpec                                 IoK8sAPIAuthorizationV1beta1SelfSubjectAccessReviewSpec
	IoK8sAPICoreV1PodIP                                                                     IoK8sAPICoreV1PodIP
	IoK8sAPIPolicyV1beta1FSGroupStrategyOptions                                             IoK8sAPIPolicyV1beta1FSGroupStrategyOptions
	IoK8sAPIPolicyV1beta1IDRange                                                            IoK8sAPIPolicyV1beta1IDRange
	IoK8sAPICoreV1NamespaceList                                                             IoK8sAPICoreV1NamespaceList
	IoK8sAPICoreV1Namespace                                                                 IoK8sAPICoreV1Namespace
	IoK8sAPIAppsV1ControllerRevision                                                        IoK8sAPIAppsV1ControllerRevision
	IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement                                  IoK8sApimachineryPkgApisMetaV1LabelSelectorRequirement
	IoK8sAPICoreV1WindowsSecurityContextOptions                                             IoK8sAPICoreV1WindowsSecurityContextOptions
	IoK8sAPIAdmissionregistrationV1ServiceReference                                         IoK8sAPIAdmissionregistrationV1ServiceReference
	IoK8sAPICoreV1PodAffinity                                                               IoK8sAPICoreV1PodAffinity
	IoK8sAPIStorageV1VolumeAttachmentSource                                                 IoK8sAPIStorageV1VolumeAttachmentSource
	IoK8sAPICoreV1ResourceFieldSelector                                                     IoK8sAPICoreV1ResourceFieldSelector
	IoK8sAPIAutoscalingV2beta1ResourceMetricStatus                                          IoK8sAPIAutoscalingV2beta1ResourceMetricStatus
	IoK8sAPICoreV1EphemeralContainer                                                        IoK8sAPICoreV1EphemeralContainer
	IoK8sAPICoreV1LocalObjectReference                                                      IoK8sAPICoreV1LocalObjectReference
	IoK8sAPIBatchV1Job                                                                      IoK8sAPIBatchV1Job
	IoK8sAPIBatchV1JobStatus                                                                IoK8sAPIBatchV1JobStatus
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionNames          IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionNames
	IoK8sAPIFlowcontrolV1beta1LimitResponse                                                 IoK8sAPIFlowcontrolV1beta1LimitResponse
	IoK8sAPIFlowcontrolV1beta1QueuingConfiguration                                          IoK8sAPIFlowcontrolV1beta1QueuingConfiguration
	IoK8sAPIStorageV1beta1CSINodeSpec                                                       IoK8sAPIStorageV1beta1CSINodeSpec
	IoK8sAPICoreV1PersistentVolumeClaimTemplate                                             IoK8sAPICoreV1PersistentVolumeClaimTemplate
	IoK8sAPINetworkingV1beta1IngressClass                                                   IoK8sAPINetworkingV1beta1IngressClass
	IoK8sAPINetworkingV1beta1IngressClassSpec                                               IoK8sAPINetworkingV1beta1IngressClassSpec
	IoK8sAPICoreV1DownwardAPIProjection                                                     IoK8sAPICoreV1DownwardAPIProjection
	IoK8sAPICoreV1DownwardAPIVolumeFile                                                     IoK8sAPICoreV1DownwardAPIVolumeFile
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceValidation          IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceValidation
	IoK8sAPICoreV1NamespaceSpec                                                             IoK8sAPICoreV1NamespaceSpec
	IoK8sAPINodeV1beta1Scheduling                                                           IoK8sAPINodeV1beta1Scheduling
	IoK8sAPICoreV1Service                                                                   IoK8sAPICoreV1Service
	IoK8sAPICoreV1ServiceSpec                                                               IoK8sAPICoreV1ServiceSpec
	IoK8sAPICoreV1ServiceStatus                                                             IoK8sAPICoreV1ServiceStatus
	IoK8sAPIAppsV1Deployment                                                                IoK8sAPIAppsV1Deployment
	IoK8sAPIAppsV1DeploymentSpec                                                            IoK8sAPIAppsV1DeploymentSpec
	IoK8sAPIAppsV1DeploymentStatus                                                          IoK8sAPIAppsV1DeploymentStatus
	IoK8sAPICoreV1SELinuxOptions                                                            IoK8sAPICoreV1SELinuxOptions
	IoK8sApimachineryPkgApisMetaV1StatusCause                                               IoK8sApimachineryPkgApisMetaV1StatusCause
	IoK8sAPIAutoscalingV2beta1MetricStatus                                                  IoK8sAPIAutoscalingV2beta1MetricStatus
	IoK8sAPIAutoscalingV2beta1ObjectMetricStatus                                            IoK8sAPIAutoscalingV2beta1ObjectMetricStatus
	IoK8sAPIAutoscalingV2beta1PodsMetricStatus                                              IoK8sAPIAutoscalingV2beta1PodsMetricStatus
	IoK8sAPIAdmissionregistrationV1beta1ValidatingWebhookConfiguration                      IoK8sAPIAdmissionregistrationV1beta1ValidatingWebhookConfiguration
	IoK8sAPIAdmissionregistrationV1beta1ValidatingWebhook                                   IoK8sAPIAdmissionregistrationV1beta1ValidatingWebhook
	IoK8sAPIAutoscalingV2beta1HorizontalPodAutoscalerStatus                                 IoK8sAPIAutoscalingV2beta1HorizontalPodAutoscalerStatus
	IoK8sAPIPolicyV1beta1Eviction                                                           IoK8sAPIPolicyV1beta1Eviction
	IoK8sAPINetworkingV1beta1IngressBackend                                                 IoK8sAPINetworkingV1beta1IngressBackend
	IoK8sAPINetworkingV1beta1IngressRule                                                    IoK8sAPINetworkingV1beta1IngressRule
	IoK8sAPIAutoscalingV2beta2HPAScalingRules                                               IoK8sAPIAutoscalingV2beta2HPAScalingRules
	IoK8sAPIAutoscalingV2beta2HPAScalingPolicy                                              IoK8sAPIAutoscalingV2beta2HPAScalingPolicy
	IoK8sAPICoordinationV1Lease                                                             IoK8sAPICoordinationV1Lease
	IoK8sAPICoordinationV1LeaseSpec                                                         IoK8sAPICoordinationV1LeaseSpec
	IoK8sAPINetworkingV1IngressServiceBackend                                               IoK8sAPINetworkingV1IngressServiceBackend
	IoK8sAPIAppsV1DaemonSet                                                                 IoK8sAPIAppsV1DaemonSet
	IoK8sAPIAppsV1DaemonSetSpec                                                             IoK8sAPIAppsV1DaemonSetSpec
	IoK8sAPIAppsV1DaemonSetStatus                                                           IoK8sAPIAppsV1DaemonSetStatus
	IoK8sAPIAdmissionregistrationV1beta1MutatingWebhook                                     IoK8sAPIAdmissionregistrationV1beta1MutatingWebhook
	IoK8sAPIAutoscalingV2beta2ExternalMetricStatus                                          IoK8sAPIAutoscalingV2beta2ExternalMetricStatus
	IoK8sAPIAutoscalingV2beta2MetricValueStatus                                             IoK8sAPIAutoscalingV2beta2MetricValueStatus
	IoK8sAPIStorageV1alpha1VolumeAttachmentSource                                           IoK8sAPIStorageV1alpha1VolumeAttachmentSource
	IoK8sAPIAuthorizationV1beta1SelfSubjectAccessReview                                     IoK8sAPIAuthorizationV1beta1SelfSubjectAccessReview
	IoK8sAPIAuthorizationV1beta1SubjectAccessReviewStatus                                   IoK8sAPIAuthorizationV1beta1SubjectAccessReviewStatus
	IoK8sAPIAutoscalingV2beta2HorizontalPodAutoscalerSpec                                   IoK8sAPIAutoscalingV2beta2HorizontalPodAutoscalerSpec
	IoK8sAPIAutoscalingV2beta2HorizontalPodAutoscalerBehavior                               IoK8sAPIAutoscalingV2beta2HorizontalPodAutoscalerBehavior
	IoK8sAPIAutoscalingV2beta2MetricSpec                                                    IoK8sAPIAutoscalingV2beta2MetricSpec
	IoK8sAPICoreV1ScopedResourceSelectorRequirement                                         IoK8sAPICoreV1ScopedResourceSelectorRequirement
	IoK8sAPICoreV1ComponentCondition                                                        IoK8sAPICoreV1ComponentCondition
	IoK8sAPICoreV1VolumeProjection                                                          IoK8sAPICoreV1VolumeProjection
	IoK8sAPICoreV1ServiceAccountTokenProjection                                             IoK8sAPICoreV1ServiceAccountTokenProjection
	IoK8sAPIFlowcontrolV1beta1FlowSchemaSpec                                                IoK8sAPIFlowcontrolV1beta1FlowSchemaSpec
	IoK8sAPIFlowcontrolV1beta1FlowDistinguisherMethod                                       IoK8sAPIFlowcontrolV1beta1FlowDistinguisherMethod
	IoK8sAPIFlowcontrolV1beta1PriorityLevelConfigurationReference                           IoK8sAPIFlowcontrolV1beta1PriorityLevelConfigurationReference
	IoK8sAPIStorageV1beta1VolumeNodeResources                                               IoK8sAPIStorageV1beta1VolumeNodeResources
	IoK8sAPIRbacV1alpha1PolicyRule                                                          IoK8sAPIRbacV1alpha1PolicyRule
	IoK8sAPIPolicyV1beta1SELinuxStrategyOptions                                             IoK8sAPIPolicyV1beta1SELinuxStrategyOptions
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionVersion   IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionVersion
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceColumnDefinition    IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceColumnDefinition
	IoK8sAPINodeV1alpha1Overhead                                                            IoK8sAPINodeV1alpha1Overhead
	IoK8sAPICoreV1LimitRangeList                                                            IoK8sAPICoreV1LimitRangeList
	IoK8sAPICoreV1LimitRange                                                                IoK8sAPICoreV1LimitRange
	IoK8sAPIFlowcontrolV1beta1FlowSchema                                                    IoK8sAPIFlowcontrolV1beta1FlowSchema
	IoK8sAPIFlowcontrolV1beta1FlowSchemaStatus                                              IoK8sAPIFlowcontrolV1beta1FlowSchemaStatus
	IoK8sAPIAuthorizationV1SelfSubjectAccessReviewSpec                                      IoK8sAPIAuthorizationV1SelfSubjectAccessReviewSpec
	IoK8sAPIBatchV1beta1CronJob                                                             IoK8sAPIBatchV1beta1CronJob
	IoK8sAPIBatchV1beta1CronJobSpec                                                         IoK8sAPIBatchV1beta1CronJobSpec
	IoK8sAPIBatchV1beta1CronJobStatus                                                       IoK8sAPIBatchV1beta1CronJobStatus
	IoK8sAPICoordinationV1beta1LeaseSpec                                                    IoK8sAPICoordinationV1beta1LeaseSpec
	IoK8sAPIAdmissionregistrationV1MutatingWebhook                                          IoK8sAPIAdmissionregistrationV1MutatingWebhook
	IoK8sApimachineryPkgApisMetaV1ManagedFieldsEntry                                        IoK8sApimachineryPkgApisMetaV1ManagedFieldsEntry
	IoK8sAPIAuthorizationV1beta1SelfSubjectRulesReviewSpec                                  IoK8sAPIAuthorizationV1beta1SelfSubjectRulesReviewSpec
	IoK8sAPINodeV1RuntimeClass                                                              IoK8sAPINodeV1RuntimeClass
	IoK8sAPINodeV1Scheduling                                                                IoK8sAPINodeV1Scheduling
	IoK8sAPIAuthenticationV1beta1TokenReviewStatus                                          IoK8sAPIAuthenticationV1beta1TokenReviewStatus
	IoK8sAPIAuthenticationV1beta1UserInfo                                                   IoK8sAPIAuthenticationV1beta1UserInfo
	IoK8sAPICoreV1EnvVarSource                                                              IoK8sAPICoreV1EnvVarSource
	IoK8sAPICoreV1ConfigMapKeySelector                                                      IoK8sAPICoreV1ConfigMapKeySelector
	IoK8sAPICoreV1ObjectFieldSelector                                                       IoK8sAPICoreV1ObjectFieldSelector
	IoK8sAPIRbacV1alpha1ClusterRole                                                         IoK8sAPIRbacV1alpha1ClusterRole
	IoK8sAPIRbacV1alpha1AggregationRule                                                     IoK8sAPIRbacV1alpha1AggregationRule
	IoK8sAPICoreV1NodeSystemInfo                                                            IoK8sAPICoreV1NodeSystemInfo
	IoK8sAPINetworkingV1NetworkPolicySpec                                                   IoK8sAPINetworkingV1NetworkPolicySpec
	IoK8sAPIFlowcontrolV1beta1PriorityLevelConfigurationCondition                           IoK8sAPIFlowcontrolV1beta1PriorityLevelConfigurationCondition
	IoK8sAPIAuthenticationV1TokenReview                                                     IoK8sAPIAuthenticationV1TokenReview
	IoK8sAPIAuthenticationV1TokenReviewSpec                                                 IoK8sAPIAuthenticationV1TokenReviewSpec
	IoK8sAPIAuthenticationV1TokenReviewStatus                                               IoK8sAPIAuthenticationV1TokenReviewStatus
	IoK8sAPIRbacV1beta1PolicyRule                                                           IoK8sAPIRbacV1beta1PolicyRule
	IoK8sAPIAppsV1RollingUpdateDaemonSet                                                    IoK8sAPIAppsV1RollingUpdateDaemonSet
	IoK8sAPISchedulingV1PriorityClass                                                       IoK8sAPISchedulingV1PriorityClass
	IoK8sAPIAppsV1ReplicaSetSpec                                                            IoK8sAPIAppsV1ReplicaSetSpec
	IoK8sAPICoreV1PodTemplateSpec                                                           IoK8sAPICoreV1PodTemplateSpec
	IoK8sAPIAuthorizationV1SubjectAccessReview                                              IoK8sAPIAuthorizationV1SubjectAccessReview
	IoK8sAPIAuthorizationV1SubjectAccessReviewStatus                                        IoK8sAPIAuthorizationV1SubjectAccessReviewStatus
	IoK8sAPICoreV1HostAlias                                                                 IoK8sAPICoreV1HostAlias
	IoK8sAPIFlowcontrolV1alpha1GroupSubject                                                 IoK8sAPIFlowcontrolV1alpha1GroupSubject
	IoK8sAPIRbacV1alpha1RoleList                                                            IoK8sAPIRbacV1alpha1RoleList
	IoK8sAPIRbacV1alpha1Role                                                                IoK8sAPIRbacV1alpha1Role
	IoK8sAPIFlowcontrolV1alpha1Subject                                                      IoK8sAPIFlowcontrolV1alpha1Subject
	IoK8sAPIFlowcontrolV1alpha1ServiceAccountSubject                                        IoK8sAPIFlowcontrolV1alpha1ServiceAccountSubject
	IoK8sAPIFlowcontrolV1alpha1UserSubject                                                  IoK8sAPIFlowcontrolV1alpha1UserSubject
	IoK8sAPIStorageV1beta1VolumeAttachment                                                  IoK8sAPIStorageV1beta1VolumeAttachment
	IoK8sAPIStorageV1beta1VolumeAttachmentSpec                                              IoK8sAPIStorageV1beta1VolumeAttachmentSpec
	IoK8sAPIAutoscalingV1HorizontalPodAutoscalerSpec                                        IoK8sAPIAutoscalingV1HorizontalPodAutoscalerSpec
	IoK8sAPIAutoscalingV1CrossVersionObjectReference                                        IoK8sAPIAutoscalingV1CrossVersionObjectReference
	IoK8sAPICoreV1Sysctl                                                                    IoK8sAPICoreV1Sysctl
	IoK8sAPINetworkingV1IPBlock                                                             IoK8sAPINetworkingV1IPBlock
	IoK8sAPICoreV1SeccompProfile                                                            IoK8sAPICoreV1SeccompProfile
	IoK8sAPIRbacV1alpha1RoleRef                                                             IoK8sAPIRbacV1alpha1RoleRef
	IoK8sAPIRbacV1alpha1Subject                                                             IoK8sAPIRbacV1alpha1Subject
	IoK8sAPIAuthenticationV1TokenRequest                                                    IoK8sAPIAuthenticationV1TokenRequest
	IoK8sAPIAuthenticationV1TokenRequestSpec                                                IoK8sAPIAuthenticationV1TokenRequestSpec
	IoK8sAPICoreV1PodReadinessGate                                                          IoK8sAPICoreV1PodReadinessGate
	IoK8sAPINetworkingV1NetworkPolicyIngressRule                                            IoK8sAPINetworkingV1NetworkPolicyIngressRule
	IoK8sAPINetworkingV1NetworkPolicyPeer                                                   IoK8sAPINetworkingV1NetworkPolicyPeer
	IoK8sAPICoreV1PersistentVolume                                                          IoK8sAPICoreV1PersistentVolume
	IoK8sAPICoreV1PersistentVolumeStatus                                                    IoK8sAPICoreV1PersistentVolumeStatus
	IoK8sAPICoreV1EndpointSubset                                                            IoK8sAPICoreV1EndpointSubset
	IoK8sAPICoreV1EndpointPort                                                              IoK8sAPICoreV1EndpointPort
	IoK8sAPIPolicyV1beta1AllowedCSIDriver                                                   IoK8sAPIPolicyV1beta1AllowedCSIDriver
	IoK8sApimachineryPkgApisMetaV1APIResourceList                                           IoK8sApimachineryPkgApisMetaV1APIResourceList
	IoK8sApimachineryPkgApisMetaV1APIResource                                               IoK8sApimachineryPkgApisMetaV1APIResource
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSONSchemaPropsOrBool                  IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSONSchemaPropsOrBool
	IoK8sAPIAuthorizationV1SelfSubjectRulesReview                                           IoK8sAPIAuthorizationV1SelfSubjectRulesReview
	IoK8sAPIAuthorizationV1SelfSubjectRulesReviewSpec                                       IoK8sAPIAuthorizationV1SelfSubjectRulesReviewSpec
	IoK8sAPIApiserverinternalV1alpha1StorageVersionList                                     IoK8sAPIApiserverinternalV1alpha1StorageVersionList
	IoK8sAPIApiserverinternalV1alpha1StorageVersion                                         IoK8sAPIApiserverinternalV1alpha1StorageVersion
	IoK8sAPIAuthorizationV1LocalSubjectAccessReview                                         IoK8sAPIAuthorizationV1LocalSubjectAccessReview
	IoK8sAPICoreV1ConfigMapList                                                             IoK8sAPICoreV1ConfigMapList
	IoK8sAPICoreV1ConfigMap                                                                 IoK8sAPICoreV1ConfigMap
	IoK8sAPIFlowcontrolV1alpha1FlowSchemaCondition                                          IoK8sAPIFlowcontrolV1alpha1FlowSchemaCondition
	IoK8sAPICoreV1SecretProjection                                                          IoK8sAPICoreV1SecretProjection
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionNames     IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionNames
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceConversion          IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceConversion
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1WebhookClientConfig               IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1WebhookClientConfig
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1ServiceReference                  IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1ServiceReference
	IoK8sAPIAdmissionregistrationV1MutatingWebhookConfiguration                             IoK8sAPIAdmissionregistrationV1MutatingWebhookConfiguration
	IoK8sAPIAdmissionregistrationV1MutatingWebhookConfigurationList                         IoK8sAPIAdmissionregistrationV1MutatingWebhookConfigurationList
	IoK8sAPINetworkingV1NetworkPolicyEgressRule                                             IoK8sAPINetworkingV1NetworkPolicyEgressRule
	IoK8sAPICoreV1ReplicationControllerList                                                 IoK8sAPICoreV1ReplicationControllerList
	IoK8sAPICoreV1ReplicationController                                                     IoK8sAPICoreV1ReplicationController
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSONSchemaPropsOrArray                 IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSONSchemaPropsOrArray
	IoK8sApimachineryPkgApisMetaV1APIVersions                                               IoK8sApimachineryPkgApisMetaV1APIVersions
	IoK8sAPIAdmissionregistrationV1ValidatingWebhookConfigurationList                       IoK8sAPIAdmissionregistrationV1ValidatingWebhookConfigurationList
	IoK8sAPIAdmissionregistrationV1ValidatingWebhookConfiguration                           IoK8sAPIAdmissionregistrationV1ValidatingWebhookConfiguration
	IoK8sAPIRbacV1beta1ClusterRoleList                                                      IoK8sAPIRbacV1beta1ClusterRoleList
	IoK8sAPIRbacV1beta1ClusterRole                                                          IoK8sAPIRbacV1beta1ClusterRole
	IoK8sAPICoreV1SessionAffinityConfig                                                     IoK8sAPICoreV1SessionAffinityConfig
	IoK8sAPICertificatesV1beta1CertificateSigningRequestSpec                                IoK8sAPICertificatesV1beta1CertificateSigningRequestSpec
	IoK8sAPIFlowcontrolV1beta1PriorityLevelConfigurationList                                IoK8sAPIFlowcontrolV1beta1PriorityLevelConfigurationList
	IoK8sAPIAppsV1StatefulSetSpec                                                           IoK8sAPIAppsV1StatefulSetSpec
	IoK8sAPICoreV1PersistentVolumeClaim                                                     IoK8sAPICoreV1PersistentVolumeClaim
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSONSchemaProps                        IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSONSchemaProps
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSON                                   IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSON
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSONSchemaPropsOrStringArray           IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSONSchemaPropsOrStringArray
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1ExternalDocumentation                  IoK8sApiextensionsApiserverPkgApisApiextensionsV1ExternalDocumentation
	IoK8sAPICoreV1EventList                                                                 IoK8sAPICoreV1EventList
	IoK8sAPICoreV1Event                                                                     IoK8sAPICoreV1Event
	IoK8sAPINetworkingV1HTTPIngressPath                                                     IoK8sAPINetworkingV1HTTPIngressPath
	IoK8sAPICoreV1AttachedVolume                                                            IoK8sAPICoreV1AttachedVolume
	IoK8sAPIAutoscalingV2beta2ObjectMetricStatus                                            IoK8sAPIAutoscalingV2beta2ObjectMetricStatus
	IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceCondition                          IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceCondition
	IoK8sAPIAppsV1DaemonSetList                                                             IoK8sAPIAppsV1DaemonSetList
	IoK8sAPIRbacV1alpha1ClusterRoleBindingList                                              IoK8sAPIRbacV1alpha1ClusterRoleBindingList
	IoK8sAPIRbacV1alpha1ClusterRoleBinding                                                  IoK8sAPIRbacV1alpha1ClusterRoleBinding
	IoK8sAPICoordinationV1beta1LeaseList                                                    IoK8sAPICoordinationV1beta1LeaseList
	IoK8sAPICoordinationV1beta1Lease                                                        IoK8sAPICoordinationV1beta1Lease
	IoK8sAPIStorageV1beta1VolumeAttachmentSource                                            IoK8sAPIStorageV1beta1VolumeAttachmentSource
	IoK8sAPIAutoscalingV1HorizontalPodAutoscalerStatus                                      IoK8sAPIAutoscalingV1HorizontalPodAutoscalerStatus
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionCondition      IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionCondition
	IoK8sAPIExtensionsV1beta1HTTPIngressPath                                                IoK8sAPIExtensionsV1beta1HTTPIngressPath
	IoK8sAPIExtensionsV1beta1IngressBackend                                                 IoK8sAPIExtensionsV1beta1IngressBackend
	IoK8sAPIAppsV1DaemonSetCondition                                                        IoK8sAPIAppsV1DaemonSetCondition
	IoK8sAPIFlowcontrolV1beta1UserSubject                                                   IoK8sAPIFlowcontrolV1beta1UserSubject
	IoK8sAPICoreV1NodeDaemonEndpoints                                                       IoK8sAPICoreV1NodeDaemonEndpoints
	IoK8sAPICoreV1ContainerImage                                                            IoK8sAPICoreV1ContainerImage
	IoK8sAPIStorageV1VolumeError                                                            IoK8sAPIStorageV1VolumeError
	IoK8sAPIRbacV1beta1Role                                                                 IoK8sAPIRbacV1beta1Role
	IoK8sAPICoreV1Capabilities                                                              IoK8sAPICoreV1Capabilities
	IoK8sAPICertificatesV1CertificateSigningRequestCondition                                IoK8sAPICertificatesV1CertificateSigningRequestCondition
	IoK8sAPIFlowcontrolV1beta1LimitedPriorityLevelConfiguration                             IoK8sAPIFlowcontrolV1beta1LimitedPriorityLevelConfiguration
	IoK8sAPIStorageV1beta1StorageClass                                                      IoK8sAPIStorageV1beta1StorageClass
	IoK8sAPICoreV1TopologySelectorTerm                                                      IoK8sAPICoreV1TopologySelectorTerm
	IoK8sAPIAppsV1StatefulSetList                                                           IoK8sAPIAppsV1StatefulSetList
	IoK8sAPIAppsV1StatefulSet                                                               IoK8sAPIAppsV1StatefulSet
	IoK8sAPIFlowcontrolV1alpha1FlowSchemaList                                               IoK8sAPIFlowcontrolV1alpha1FlowSchemaList
	IoK8sAPIFlowcontrolV1alpha1FlowSchema                                                   IoK8sAPIFlowcontrolV1alpha1FlowSchema
	IoK8sAPIAutoscalingV2beta2ResourceMetricSource                                          IoK8sAPIAutoscalingV2beta2ResourceMetricSource
	IoK8sAPICoreV1EventSeries                                                               IoK8sAPICoreV1EventSeries
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionSpec      IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionSpec
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionStatus    IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionStatus
	IoK8sAPICoreV1NodeList                                                                  IoK8sAPICoreV1NodeList
	IoK8sAPINetworkingV1beta1HTTPIngressPath                                                IoK8sAPINetworkingV1beta1HTTPIngressPath
	IoK8sAPIAuthenticationV1BoundObjectReference                                            IoK8sAPIAuthenticationV1BoundObjectReference
	IoK8sAPICoreV1TopologySpreadConstraint                                                  IoK8sAPICoreV1TopologySpreadConstraint
	IoK8sAPICoordinationV1LeaseList                                                         IoK8sAPICoordinationV1LeaseList
	IoK8sAPICoreV1Affinity                                                                  IoK8sAPICoreV1Affinity
	IoK8sAPICoreV1PodSecurityContext                                                        IoK8sAPICoreV1PodSecurityContext
	IoK8sAPINetworkingV1HTTPIngressRuleValue                                                IoK8sAPINetworkingV1HTTPIngressRuleValue
	IoK8sAPIAutoscalingV2beta2PodsMetricSource                                              IoK8sAPIAutoscalingV2beta2PodsMetricSource
	IoK8sAPIAuthenticationV1beta1TokenReviewSpec                                            IoK8sAPIAuthenticationV1beta1TokenReviewSpec
	IoK8sAPICoreV1SecretEnvSource                                                           IoK8sAPICoreV1SecretEnvSource
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceValidation               IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceValidation
	IoK8sAPIAutoscalingV2beta1ResourceMetricSource                                          IoK8sAPIAutoscalingV2beta1ResourceMetricSource
	IoK8sAPIStorageV1beta1CSINodeDriver                                                     IoK8sAPIStorageV1beta1CSINodeDriver
	IoK8sAPIAuthorizationV1beta1NonResourceRule                                             IoK8sAPIAuthorizationV1beta1NonResourceRule
	IoK8sAPIStorageV1beta1CSIDriverList                                                     IoK8sAPIStorageV1beta1CSIDriverList
	IoK8sApimachineryPkgApisMetaV1Status                                                    IoK8sApimachineryPkgApisMetaV1Status
	IoK8sApimachineryPkgApisMetaV1StatusDetails                                             IoK8sApimachineryPkgApisMetaV1StatusDetails
	IoK8sAPIPolicyV1beta1PodSecurityPolicyList                                              IoK8sAPIPolicyV1beta1PodSecurityPolicyList
	IoK8sAPIPolicyV1beta1PodSecurityPolicy                                                  IoK8sAPIPolicyV1beta1PodSecurityPolicy
	IoK8sAPIAppsV1DeploymentCondition                                                       IoK8sAPIAppsV1DeploymentCondition
	IoK8sAPIExtensionsV1beta1IngressList                                                    IoK8sAPIExtensionsV1beta1IngressList
	IoK8sAPICoreV1ConfigMapEnvSource                                                        IoK8sAPICoreV1ConfigMapEnvSource
	IoK8sAPIStorageV1beta1VolumeAttachmentList                                              IoK8sAPIStorageV1beta1VolumeAttachmentList
	IoK8sAPIAutoscalingV1ScaleStatus                                                        IoK8sAPIAutoscalingV1ScaleStatus
	IoK8sAPICoreV1ConfigMapProjection                                                       IoK8sAPICoreV1ConfigMapProjection
	IoK8sAPIBatchV2alpha1CronJobList                                                        IoK8sAPIBatchV2alpha1CronJobList
	IoK8sAPIBatchV2alpha1CronJob                                                            IoK8sAPIBatchV2alpha1CronJob
	IoK8sAPIAutoscalingV2beta1HorizontalPodAutoscaler                                       IoK8sAPIAutoscalingV2beta1HorizontalPodAutoscaler
	IoK8sAPIAutoscalingV2beta1HorizontalPodAutoscalerSpec                                   IoK8sAPIAutoscalingV2beta1HorizontalPodAutoscalerSpec
	IoK8sAPIFlowcontrolV1alpha1LimitedPriorityLevelConfiguration                            IoK8sAPIFlowcontrolV1alpha1LimitedPriorityLevelConfiguration
	IoK8sAPICoreV1ComponentStatus                                                           IoK8sAPICoreV1ComponentStatus
	IoK8sAPICoreV1ReplicationControllerSpec                                                 IoK8sAPICoreV1ReplicationControllerSpec
	IoK8sAPIFlowcontrolV1beta1FlowSchemaCondition                                           IoK8sAPIFlowcontrolV1beta1FlowSchemaCondition
	IoK8sApimachineryPkgApisMetaV1Patch                                                     IoK8sApimachineryPkgApisMetaV1Patch
	IoK8sAPIFlowcontrolV1alpha1NonResourcePolicyRule                                        IoK8sAPIFlowcontrolV1alpha1NonResourcePolicyRule
	IoK8sAPIFlowcontrolV1alpha1ResourcePolicyRule                                           IoK8sAPIFlowcontrolV1alpha1ResourcePolicyRule
	IoK8sAPICertificatesV1CertificateSigningRequestList                                     IoK8sAPICertificatesV1CertificateSigningRequestList
	IoK8sAPICertificatesV1CertificateSigningRequest                                         IoK8sAPICertificatesV1CertificateSigningRequest
	IoK8sAPICoreV1LimitRangeItem                                                            IoK8sAPICoreV1LimitRangeItem
	IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceSpec                          IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceSpec
	IoK8sAPIExtensionsV1beta1HTTPIngressRuleValue                                           IoK8sAPIExtensionsV1beta1HTTPIngressRuleValue
	IoK8sAPIStorageV1beta1StorageClassList                                                  IoK8sAPIStorageV1beta1StorageClassList
	IoK8sAPICertificatesV1CertificateSigningRequestStatus                                   IoK8sAPICertificatesV1CertificateSigningRequestStatus
	IoK8sAPIPolicyV1beta1SupplementalGroupsStrategyOptions                                  IoK8sAPIPolicyV1beta1SupplementalGroupsStrategyOptions
	IoK8sAPICoreV1DaemonEndpoint                                                            IoK8sAPICoreV1DaemonEndpoint
	IoK8sAPINodeV1alpha1RuntimeClassList                                                    IoK8sAPINodeV1alpha1RuntimeClassList
	IoK8sAPINodeV1alpha1RuntimeClass                                                        IoK8sAPINodeV1alpha1RuntimeClass
	IoK8sAPIExtensionsV1beta1IngressRule                                                    IoK8sAPIExtensionsV1beta1IngressRule
	IoK8sAPIAutoscalingV2beta2HorizontalPodAutoscalerStatus                                 IoK8sAPIAutoscalingV2beta2HorizontalPodAutoscalerStatus
	IoK8sAPICoreV1HTTPHeader                                                                IoK8sAPICoreV1HTTPHeader
	IoK8sAPICoreV1PodCondition                                                              IoK8sAPICoreV1PodCondition
	IoK8sKubeAggregatorPkgApisApiregistrationV1ServiceReference                             IoK8sKubeAggregatorPkgApisApiregistrationV1ServiceReference
	IoK8sAPIAutoscalingV2beta2ContainerResourceMetricStatus                                 IoK8sAPIAutoscalingV2beta2ContainerResourceMetricStatus
	IoK8sAPIAutoscalingV2beta1MetricSpec                                                    IoK8sAPIAutoscalingV2beta1MetricSpec
	IoK8sAPIStorageV1CSINode                                                                IoK8sAPIStorageV1CSINode
	IoK8sAPIStorageV1CSINodeSpec                                                            IoK8sAPIStorageV1CSINodeSpec
	IoK8sAPIAutoscalingV2beta2ContainerResourceMetricSource                                 IoK8sAPIAutoscalingV2beta2ContainerResourceMetricSource
	IoK8sAPIRbacV1alpha1ClusterRoleList                                                     IoK8sAPIRbacV1alpha1ClusterRoleList
	IoK8sAPIAuthorizationV1SelfSubjectAccessReview                                          IoK8sAPIAuthorizationV1SelfSubjectAccessReview
	IoK8sAPIAdmissionregistrationV1beta1ValidatingWebhookConfigurationList                  IoK8sAPIAdmissionregistrationV1beta1ValidatingWebhookConfigurationList
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionVersion        IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceDefinitionVersion
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition         IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceColumnDefinition
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresources             IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresources
	IoK8sAPINodeV1alpha1RuntimeClassSpec                                                    IoK8sAPINodeV1alpha1RuntimeClassSpec
	IoK8sAPIAuthorizationV1beta1LocalSubjectAccessReview                                    IoK8sAPIAuthorizationV1beta1LocalSubjectAccessReview
	IoK8sAPICoreV1ClientIPConfig                                                            IoK8sAPICoreV1ClientIPConfig
	IoK8sAPICertificatesV1CertificateSigningRequestSpec                                     IoK8sAPICertificatesV1CertificateSigningRequestSpec
	IoK8sAPICoreV1ServiceList                                                               IoK8sAPICoreV1ServiceList
	IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceSpec                               IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceSpec
	IoK8sAPIRbacV1ClusterRoleList                                                           IoK8sAPIRbacV1ClusterRoleList
	IoK8sAPINetworkingV1ServiceBackendPort                                                  IoK8sAPINetworkingV1ServiceBackendPort
	IoK8sAPIFlowcontrolV1beta1ServiceAccountSubject                                         IoK8sAPIFlowcontrolV1beta1ServiceAccountSubject
	IoK8sAPIStorageV1TokenRequest                                                           IoK8sAPIStorageV1TokenRequest
	IoK8sAPIAutoscalingV2beta2HorizontalPodAutoscalerCondition                              IoK8sAPIAutoscalingV2beta2HorizontalPodAutoscalerCondition
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionCondition IoK8sApiextensionsApiserverPkgApisApiextensionsV1beta1CustomResourceDefinitionCondition
	IoK8sAPICoreV1Endpoints                                                                 IoK8sAPICoreV1Endpoints
	IoK8sAPIFlowcontrolV1alpha1PriorityLevelConfiguration                                   IoK8sAPIFlowcontrolV1alpha1PriorityLevelConfiguration
	IoK8sAPIFlowcontrolV1alpha1PriorityLevelConfigurationSpec                               IoK8sAPIFlowcontrolV1alpha1PriorityLevelConfigurationSpec
	IoK8sAPIAutoscalingV1ScaleSpec                                                          IoK8sAPIAutoscalingV1ScaleSpec
	IoK8sAPIStorageV1beta1TokenRequest                                                      IoK8sAPIStorageV1beta1TokenRequest
	IoK8sAPINetworkingV1beta1HTTPIngressRuleValue                                           IoK8sAPINetworkingV1beta1HTTPIngressRuleValue
	IoK8sAPIFlowcontrolV1alpha1FlowSchemaStatus                                             IoK8sAPIFlowcontrolV1alpha1FlowSchemaStatus
	IoK8sAPIAppsV1DeploymentList                                                            IoK8sAPIAppsV1DeploymentList
	IoK8sAPICoreV1PodAntiAffinity                                                           IoK8sAPICoreV1PodAntiAffinity
	IoK8sAPIAutoscalingV2beta1HorizontalPodAutoscalerList                                   IoK8sAPIAutoscalingV2beta1HorizontalPodAutoscalerList
	IoK8sAPICoreV1PortStatus                                                                IoK8sAPICoreV1PortStatus
	IoK8sAPIAuthorizationV1beta1SubjectAccessReview                                         IoK8sAPIAuthorizationV1beta1SubjectAccessReview
	IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceList                          IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIServiceList
	IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIService                              IoK8sKubeAggregatorPkgApisApiregistrationV1beta1APIService
	IoK8sAPIRbacV1ClusterRoleBindingList                                                    IoK8sAPIRbacV1ClusterRoleBindingList
	IoK8sAPIAppsV1ControllerRevisionList                                                    IoK8sAPIAppsV1ControllerRevisionList
	IoK8sAPIFlowcontrolV1alpha1PriorityLevelConfigurationList                               IoK8sAPIFlowcontrolV1alpha1PriorityLevelConfigurationList
	IoK8sAPIRbacV1beta1AggregationRule                                                      IoK8sAPIRbacV1beta1AggregationRule
	IoK8sAPIAuthorizationV1beta1ResourceRule                                                IoK8sAPIAuthorizationV1beta1ResourceRule
	IoK8sKubeAggregatorPkgApisApiregistrationV1APIService                                   IoK8sKubeAggregatorPkgApisApiregistrationV1APIService
	IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceStatus                             IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceStatus
	IoK8sAPINetworkingV1IngressList                                                         IoK8sAPINetworkingV1IngressList
	IoK8sAPIDiscoveryV1beta1EndpointSliceList                                               IoK8sAPIDiscoveryV1beta1EndpointSliceList
	IoK8sAPIPolicyV1beta1RunAsUserStrategyOptions                                           IoK8sAPIPolicyV1beta1RunAsUserStrategyOptions
	IoK8sAPIStorageV1StorageClassList                                                       IoK8sAPIStorageV1StorageClassList
	IoK8sAPIStorageV1StorageClass                                                           IoK8sAPIStorageV1StorageClass
	IoK8sAPICoreV1PersistentVolumeClaimStatus                                               IoK8sAPICoreV1PersistentVolumeClaimStatus
	IoK8sAPICoreV1PersistentVolumeClaimCondition                                            IoK8sAPICoreV1PersistentVolumeClaimCondition
	IoK8sAPICertificatesV1beta1CertificateSigningRequest                                    IoK8sAPICertificatesV1beta1CertificateSigningRequest
	IoK8sAPIPolicyV1beta1AllowedFlexVolume                                                  IoK8sAPIPolicyV1beta1AllowedFlexVolume
	IoK8sAPICoreV1ComponentStatusList                                                       IoK8sAPICoreV1ComponentStatusList
	IoK8sAPIStorageV1CSINodeDriver                                                          IoK8sAPIStorageV1CSINodeDriver
	IoK8sAPIAutoscalingV2beta1ContainerResourceMetricSource                                 IoK8sAPIAutoscalingV2beta1ContainerResourceMetricSource
	IoK8sAPIAutoscalingV2beta1ExternalMetricSource                                          IoK8sAPIAutoscalingV2beta1ExternalMetricSource
	IoK8sAPIAutoscalingV2beta1ObjectMetricSource                                            IoK8sAPIAutoscalingV2beta1ObjectMetricSource
	IoK8sAPIAutoscalingV2beta1PodsMetricSource                                              IoK8sAPIAutoscalingV2beta1PodsMetricSource
	IoK8sAPICoreV1PersistentVolumeList                                                      IoK8sAPICoreV1PersistentVolumeList
	IoK8sAPIBatchV1JobCondition                                                             IoK8sAPIBatchV1JobCondition
	IoK8sApimachineryPkgApisMetaV1Condition                                                 IoK8sApimachineryPkgApisMetaV1Condition
	IoK8sAPIBatchV1beta1CronJobList                                                         IoK8sAPIBatchV1beta1CronJobList
	IoK8sApimachineryPkgApisMetaV1FieldsV1                                                  IoK8sApimachineryPkgApisMetaV1FieldsV1
	IoK8sAPINetworkingV1beta1IngressClassList                                               IoK8sAPINetworkingV1beta1IngressClassList
	IoK8sAPIAdmissionregistrationV1beta1RuleWithOperations                                  IoK8sAPIAdmissionregistrationV1beta1RuleWithOperations
	IoK8sAPIBatchV2alpha1CronJobSpec                                                        IoK8sAPIBatchV2alpha1CronJobSpec
	IoK8sAPIBatchV2alpha1JobTemplateSpec                                                    IoK8sAPIBatchV2alpha1JobTemplateSpec
	IoK8sApimachineryPkgApisMetaV1WatchEvent                                                IoK8sApimachineryPkgApisMetaV1WatchEvent
	IoK8sAPIAuthenticationV1beta1TokenReview                                                IoK8sAPIAuthenticationV1beta1TokenReview
	IoK8sAPIStorageV1CSIDriverSpec                                                          IoK8sAPIStorageV1CSIDriverSpec
	IoK8sAPICoreV1LimitRangeSpec                                                            IoK8sAPICoreV1LimitRangeSpec
	IoK8sAPIStorageV1alpha1VolumeError                                                      IoK8sAPIStorageV1alpha1VolumeError
	IoK8sAPIStorageV1alpha1VolumeAttachmentSpec                                             IoK8sAPIStorageV1alpha1VolumeAttachmentSpec
	IoK8sAPIEventsV1EventList                                                               IoK8sAPIEventsV1EventList
	IoK8sAPIAutoscalingV2beta2ResourceMetricStatus                                          IoK8sAPIAutoscalingV2beta2ResourceMetricStatus
	IoK8sAPIStorageV1VolumeAttachmentList                                                   IoK8sAPIStorageV1VolumeAttachmentList
	IoK8sAPIAutoscalingV1Scale                                                              IoK8sAPIAutoscalingV1Scale
	IoK8sAPIStorageV1VolumeNodeResources                                                    IoK8sAPIStorageV1VolumeNodeResources
	IoK8sAPIPolicyV1beta1RunAsGroupStrategyOptions                                          IoK8sAPIPolicyV1beta1RunAsGroupStrategyOptions
	IoK8sApimachineryPkgVersionInfo                                                         IoK8sApimachineryPkgVersionInfo
	IoK8sAPINodeV1beta1Overhead                                                             IoK8sAPINodeV1beta1Overhead
	IoK8sAPIStorageV1alpha1VolumeAttachmentStatus                                           IoK8sAPIStorageV1alpha1VolumeAttachmentStatus
	IoK8sAPIPolicyV1beta1HostPortRange                                                      IoK8sAPIPolicyV1beta1HostPortRange
	IoK8sAPIAppsV1DaemonSetUpdateStrategy                                                   IoK8sAPIAppsV1DaemonSetUpdateStrategy
	IoK8sAPIBatchV1JobList                                                                  IoK8sAPIBatchV1JobList
	IoK8sAPINodeV1RuntimeClassList                                                          IoK8sAPINodeV1RuntimeClassList
	IoK8sAPICoreV1Taint                                                                     IoK8sAPICoreV1Taint
	IoK8sAPICoreV1EndpointsList                                                             IoK8sAPICoreV1EndpointsList
	IoK8sAPIPolicyV1beta1PodDisruptionBudgetList                                            IoK8sAPIPolicyV1beta1PodDisruptionBudgetList
	IoK8sAPISchedulingV1alpha1PriorityClassList                                             IoK8sAPISchedulingV1alpha1PriorityClassList
	IoK8sAPIStorageV1CSINodeList                                                            IoK8sAPIStorageV1CSINodeList
	IoK8sAPIEventsV1beta1EventList                                                          IoK8sAPIEventsV1beta1EventList
	IoK8sAPICoreV1Binding                                                                   IoK8sAPICoreV1Binding
	IoK8sAPIRbacV1RoleList                                                                  IoK8sAPIRbacV1RoleList
	IoK8sAPISchedulingV1PriorityClassList                                                   IoK8sAPISchedulingV1PriorityClassList
	IoK8sAPIRbacV1beta1ClusterRoleBindingList                                               IoK8sAPIRbacV1beta1ClusterRoleBindingList
	IoK8sAPICoreV1PersistentVolumeClaimList                                                 IoK8sAPICoreV1PersistentVolumeClaimList
	IoK8sAPIAutoscalingV2beta2PodsMetricStatus                                              IoK8sAPIAutoscalingV2beta2PodsMetricStatus
	IoK8sAPINetworkingV1beta1IngressList                                                    IoK8sAPINetworkingV1beta1IngressList
	IoK8sAPIPolicyV1beta1PodSecurityPolicySpec                                              IoK8sAPIPolicyV1beta1PodSecurityPolicySpec
	IoK8sAPINetworkingV1IngressClassList                                                    IoK8sAPINetworkingV1IngressClassList
	IoK8sAPINetworkingV1IngressClass                                                        IoK8sAPINetworkingV1IngressClass
	IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceList                               IoK8sKubeAggregatorPkgApisApiregistrationV1APIServiceList
	IoK8sAPIAuthorizationV1beta1SubjectRulesReviewStatus                                    IoK8sAPIAuthorizationV1beta1SubjectRulesReviewStatus
	IoK8sAPIRbacV1beta1RoleList                                                             IoK8sAPIRbacV1beta1RoleList
	IoK8sAPIFlowcontrolV1beta1FlowSchemaList                                                IoK8sAPIFlowcontrolV1beta1FlowSchemaList
	IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceScale         IoK8sApiextensionsApiserverPkgApisApiextensionsV1CustomResourceSubresourceScale
	IoK8sAPICoreV1ResourceQuotaList                                                         IoK8sAPICoreV1ResourceQuotaList
	IoK8sAPIAutoscalingV2beta2MetricStatus                                                  IoK8sAPIAutoscalingV2beta2MetricStatus
	IoK8sAPIAuthorizationV1beta1SelfSubjectRulesReview                                      IoK8sAPIAuthorizationV1beta1SelfSubjectRulesReview
	IoK8sAPICertificatesV1beta1CertificateSigningRequestList                                IoK8sAPICertificatesV1beta1CertificateSigningRequestList
}
