// Code generated by go-swagger; DO NOT EDIT.

package v1_20

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IoK8sAPINetworkingV1HTTPIngressPath HTTPIngressPath associates a path with a backend. Incoming urls matching the path are forwarded to the backend.
//
// swagger:model io.k8s.api.networking.v1.HTTPIngressPath
type IoK8sAPINetworkingV1HTTPIngressPath struct {

	// Backend defines the referenced service endpoint to which the traffic will be forwarded to.
	// Required: true
	Backend *IoK8sAPINetworkingV1IngressBackend `json:"backend"`

	// Path is matched against the path of an incoming request. Currently it can contain characters disallowed from the conventional "path" part of a URL as defined by RFC 3986. Paths must begin with a '/' and must be present when using PathType with value "Exact" or "Prefix".
	Path string `json:"path,omitempty"`

	// PathType determines the interpretation of the Path matching. PathType can be one of the following values: * Exact: Matches the URL path exactly. * Prefix: Matches based on a URL path prefix split by '/'. Matching is
	//   done on a path element by element basis. A path element refers is the
	//   list of labels in the path split by the '/' separator. A request is a
	//   match for path p if every p is an element-wise prefix of p of the
	//   request path. Note that if the last element of the path is a substring
	//   of the last element in request path, it is not a match (e.g. /foo/bar
	//   matches /foo/bar/baz, but does not match /foo/barbaz).
	// * ImplementationSpecific: Interpretation of the Path matching is up to
	//   the IngressClass. Implementations can treat this as a separate PathType
	//   or treat it identically to Prefix or Exact path types.
	// Implementations are required to support all path types.
	// Required: true
	PathType *string `json:"pathType"`
}

// Validate validates this io k8s api networking v1 HTTP ingress path
func (m *IoK8sAPINetworkingV1HTTPIngressPath) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBackend(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePathType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoK8sAPINetworkingV1HTTPIngressPath) validateBackend(formats strfmt.Registry) error {

	if err := validate.Required("backend", "body", m.Backend); err != nil {
		return err
	}

	if m.Backend != nil {
		if err := m.Backend.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("backend")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("backend")
			}
			return err
		}
	}

	return nil
}

func (m *IoK8sAPINetworkingV1HTTPIngressPath) validatePathType(formats strfmt.Registry) error {

	if err := validate.Required("pathType", "body", m.PathType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this io k8s api networking v1 HTTP ingress path based on the context it is used
func (m *IoK8sAPINetworkingV1HTTPIngressPath) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBackend(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoK8sAPINetworkingV1HTTPIngressPath) contextValidateBackend(ctx context.Context, formats strfmt.Registry) error {

	if m.Backend != nil {
		if err := m.Backend.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("backend")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("backend")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *IoK8sAPINetworkingV1HTTPIngressPath) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoK8sAPINetworkingV1HTTPIngressPath) UnmarshalBinary(b []byte) error {
	var res IoK8sAPINetworkingV1HTTPIngressPath
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
