// Code generated by go-swagger; DO NOT EDIT.

package v1_20

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IoK8sAPIDiscoveryV1beta1ForZone ForZone provides information about which zones should consume this endpoint.
//
// swagger:model io.k8s.api.discovery.v1beta1.ForZone
type IoK8sAPIDiscoveryV1beta1ForZone struct {

	// name represents the name of the zone.
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this io k8s api discovery v1beta1 for zone
func (m *IoK8sAPIDiscoveryV1beta1ForZone) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoK8sAPIDiscoveryV1beta1ForZone) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this io k8s api discovery v1beta1 for zone based on context it is used
func (m *IoK8sAPIDiscoveryV1beta1ForZone) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IoK8sAPIDiscoveryV1beta1ForZone) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoK8sAPIDiscoveryV1beta1ForZone) UnmarshalBinary(b []byte) error {
	var res IoK8sAPIDiscoveryV1beta1ForZone
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
