// Code generated by go-swagger; DO NOT EDIT.

package v1_20

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IoK8sAPICoreV1SELinuxOptions SELinuxOptions are the labels to be applied to the container
//
// swagger:model io.k8s.api.core.v1.SELinuxOptions
type IoK8sAPICoreV1SELinuxOptions struct {

	// Level is SELinux level label that applies to the container.
	Level string `json:"level,omitempty"`

	// Role is a SELinux role label that applies to the container.
	Role string `json:"role,omitempty"`

	// Type is a SELinux type label that applies to the container.
	Type string `json:"type,omitempty"`

	// User is a SELinux user label that applies to the container.
	User string `json:"user,omitempty"`
}

// Validate validates this io k8s api core v1 s e linux options
func (m *IoK8sAPICoreV1SELinuxOptions) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this io k8s api core v1 s e linux options based on context it is used
func (m *IoK8sAPICoreV1SELinuxOptions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IoK8sAPICoreV1SELinuxOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoK8sAPICoreV1SELinuxOptions) UnmarshalBinary(b []byte) error {
	var res IoK8sAPICoreV1SELinuxOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
