// Code generated by go-swagger; DO NOT EDIT.

package v1_20

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// IoK8sApimachineryPkgApisMetaV1Patch Patch is provided to give a concrete name and type to the Kubernetes PATCH request body.
//
// swagger:model io.k8s.apimachinery.pkg.apis.meta.v1.Patch
type IoK8sApimachineryPkgApisMetaV1Patch interface{}
