// Code generated by go-swagger; DO NOT EDIT.

package v1_20

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IoK8sAPIPolicyV1beta1PodDisruptionBudgetSpec PodDisruptionBudgetSpec is a description of a PodDisruptionBudget.
//
// swagger:model io.k8s.api.policy.v1beta1.PodDisruptionBudgetSpec
type IoK8sAPIPolicyV1beta1PodDisruptionBudgetSpec struct {

	// An eviction is allowed if at most "maxUnavailable" pods selected by "selector" are unavailable after the eviction, i.e. even in absence of the evicted pod. For example, one can prevent all voluntary evictions by specifying 0. This is a mutually exclusive setting with "minAvailable".
	MaxUnavailable IoK8sApimachineryPkgUtilIntstrIntOrString `json:"maxUnavailable,omitempty"`

	// An eviction is allowed if at least "minAvailable" pods selected by "selector" will still be available after the eviction, i.e. even in the absence of the evicted pod.  So for example you can prevent all voluntary evictions by specifying "100%".
	MinAvailable IoK8sApimachineryPkgUtilIntstrIntOrString `json:"minAvailable,omitempty"`

	// Label query over pods whose evictions are managed by the disruption budget. A null selector selects no pods. An empty selector ({}) also selects no pods, which differs from standard behavior of selecting all pods. In policy/v1, an empty selector will select all pods in the namespace.
	Selector *IoK8sApimachineryPkgApisMetaV1LabelSelector `json:"selector,omitempty"`
}

// Validate validates this io k8s api policy v1beta1 pod disruption budget spec
func (m *IoK8sAPIPolicyV1beta1PodDisruptionBudgetSpec) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMaxUnavailable(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMinAvailable(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSelector(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoK8sAPIPolicyV1beta1PodDisruptionBudgetSpec) validateMaxUnavailable(formats strfmt.Registry) error {
	if swag.IsZero(m.MaxUnavailable) { // not required
		return nil
	}

	if err := m.MaxUnavailable.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("maxUnavailable")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("maxUnavailable")
		}
		return err
	}

	return nil
}

func (m *IoK8sAPIPolicyV1beta1PodDisruptionBudgetSpec) validateMinAvailable(formats strfmt.Registry) error {
	if swag.IsZero(m.MinAvailable) { // not required
		return nil
	}

	if err := m.MinAvailable.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("minAvailable")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("minAvailable")
		}
		return err
	}

	return nil
}

func (m *IoK8sAPIPolicyV1beta1PodDisruptionBudgetSpec) validateSelector(formats strfmt.Registry) error {
	if swag.IsZero(m.Selector) { // not required
		return nil
	}

	if m.Selector != nil {
		if err := m.Selector.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("selector")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("selector")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this io k8s api policy v1beta1 pod disruption budget spec based on the context it is used
func (m *IoK8sAPIPolicyV1beta1PodDisruptionBudgetSpec) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMaxUnavailable(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMinAvailable(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSelector(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoK8sAPIPolicyV1beta1PodDisruptionBudgetSpec) contextValidateMaxUnavailable(ctx context.Context, formats strfmt.Registry) error {

	if err := m.MaxUnavailable.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("maxUnavailable")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("maxUnavailable")
		}
		return err
	}

	return nil
}

func (m *IoK8sAPIPolicyV1beta1PodDisruptionBudgetSpec) contextValidateMinAvailable(ctx context.Context, formats strfmt.Registry) error {

	if err := m.MinAvailable.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("minAvailable")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("minAvailable")
		}
		return err
	}

	return nil
}

func (m *IoK8sAPIPolicyV1beta1PodDisruptionBudgetSpec) contextValidateSelector(ctx context.Context, formats strfmt.Registry) error {

	if m.Selector != nil {
		if err := m.Selector.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("selector")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("selector")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *IoK8sAPIPolicyV1beta1PodDisruptionBudgetSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoK8sAPIPolicyV1beta1PodDisruptionBudgetSpec) UnmarshalBinary(b []byte) error {
	var res IoK8sAPIPolicyV1beta1PodDisruptionBudgetSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
