// Code generated by go-swagger; DO NOT EDIT.

package v1_20

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IoK8sAPIStorageV1beta1CSINodeSpec CSINodeSpec holds information about the specification of all CSI drivers installed on a node
//
// swagger:model io.k8s.api.storage.v1beta1.CSINodeSpec
type IoK8sAPIStorageV1beta1CSINodeSpec struct {

	// drivers is a list of information of all CSI Drivers existing on a node. If all drivers in the list are uninstalled, this can become empty.
	// Required: true
	Drivers []*IoK8sAPIStorageV1beta1CSINodeDriver `json:"drivers" json,yaml:"drivers"`
}

// Validate validates this io k8s api storage v1beta1 c s i node spec
func (m *IoK8sAPIStorageV1beta1CSINodeSpec) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDrivers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoK8sAPIStorageV1beta1CSINodeSpec) validateDrivers(formats strfmt.Registry) error {

	if err := validate.Required("drivers", "body", m.Drivers); err != nil {
		return err
	}

	for i := 0; i < len(m.Drivers); i++ {
		if swag.IsZero(m.Drivers[i]) { // not required
			continue
		}

		if m.Drivers[i] != nil {
			if err := m.Drivers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("drivers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("drivers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this io k8s api storage v1beta1 c s i node spec based on the context it is used
func (m *IoK8sAPIStorageV1beta1CSINodeSpec) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDrivers(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoK8sAPIStorageV1beta1CSINodeSpec) contextValidateDrivers(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Drivers); i++ {

		if m.Drivers[i] != nil {
			if err := m.Drivers[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("drivers" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("drivers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *IoK8sAPIStorageV1beta1CSINodeSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoK8sAPIStorageV1beta1CSINodeSpec) UnmarshalBinary(b []byte) error {
	var res IoK8sAPIStorageV1beta1CSINodeSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
