// Code generated by go-swagger; DO NOT EDIT.

package v1_20

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IoK8sAPIBatchV1UncountedTerminatedPods UncountedTerminatedPods holds UIDs of Pods that have terminated but haven't been accounted in Job status counters.
//
// swagger:model io.k8s.api.batch.v1.UncountedTerminatedPods
type IoK8sAPIBatchV1UncountedTerminatedPods struct {

	// Failed holds UIDs of failed Pods.
	Failed []string `json:"failed"`

	// Succeeded holds UIDs of succeeded Pods.
	Succeeded []string `json:"succeeded"`
}

// Validate validates this io k8s api batch v1 uncounted terminated pods
func (m *IoK8sAPIBatchV1UncountedTerminatedPods) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this io k8s api batch v1 uncounted terminated pods based on context it is used
func (m *IoK8sAPIBatchV1UncountedTerminatedPods) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IoK8sAPIBatchV1UncountedTerminatedPods) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoK8sAPIBatchV1UncountedTerminatedPods) UnmarshalBinary(b []byte) error {
	var res IoK8sAPIBatchV1UncountedTerminatedPods
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
