// Code generated by go-swagger; DO NOT EDIT.

package v1_20

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSON JSON represents any valid JSON value. These types are supported: bool, int64, float64, string, []interface{}, map[string]interface{} and nil.
//
// swagger:model io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSON
type IoK8sApiextensionsApiserverPkgApisApiextensionsV1JSON interface{}
