// Code generated by go-swagger; DO NOT EDIT.

package v1_20

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IoK8sAPIFlowcontrolV1beta2PriorityLevelConfigurationReference PriorityLevelConfigurationReference contains information that points to the "request-priority" being used.
//
// swagger:model io.k8s.api.flowcontrol.v1beta2.PriorityLevelConfigurationReference
type IoK8sAPIFlowcontrolV1beta2PriorityLevelConfigurationReference struct {

	// `name` is the name of the priority level configuration being referenced Required.
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this io k8s api flowcontrol v1beta2 priority level configuration reference
func (m *IoK8sAPIFlowcontrolV1beta2PriorityLevelConfigurationReference) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoK8sAPIFlowcontrolV1beta2PriorityLevelConfigurationReference) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this io k8s api flowcontrol v1beta2 priority level configuration reference based on context it is used
func (m *IoK8sAPIFlowcontrolV1beta2PriorityLevelConfigurationReference) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IoK8sAPIFlowcontrolV1beta2PriorityLevelConfigurationReference) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoK8sAPIFlowcontrolV1beta2PriorityLevelConfigurationReference) UnmarshalBinary(b []byte) error {
	var res IoK8sAPIFlowcontrolV1beta2PriorityLevelConfigurationReference
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
