// Code generated by go-swagger; DO NOT EDIT.

package v1_20

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IoK8sAPICoreV1ContainerImage Describe a container image
//
// swagger:model io.k8s.api.core.v1.ContainerImage
type IoK8sAPICoreV1ContainerImage struct {

	// Names by which this image is known. e.g. ["k8s.gcr.io/hyperkube:v1.0.7", "dockerhub.io/google_containers/hyperkube:v1.0.7"]
	Names []string `json:"names"`

	// The size of the image in bytes.
	SizeBytes int64 `json:"sizeBytes,omitempty"`
}

// Validate validates this io k8s api core v1 container image
func (m *IoK8sAPICoreV1ContainerImage) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this io k8s api core v1 container image based on context it is used
func (m *IoK8sAPICoreV1ContainerImage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IoK8sAPICoreV1ContainerImage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoK8sAPICoreV1ContainerImage) UnmarshalBinary(b []byte) error {
	var res IoK8sAPICoreV1ContainerImage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
