// Code generated by go-swagger; DO NOT EDIT.

package v1_20

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IoK8sKubeAggregatorPkgApisApiregistrationV1beta1ServiceReference ServiceReference holds a reference to Service.legacy.k8s.io
//
// swagger:model io.k8s.kube-aggregator.pkg.apis.apiregistration.v1beta1.ServiceReference
type IoK8sKubeAggregatorPkgApisApiregistrationV1beta1ServiceReference struct {

	// Name is the name of the service
	Name string `json:"name,omitempty" json,yaml:"name,omitempty"`

	// Namespace is the namespace of the service
	Namespace string `json:"namespace,omitempty" json,yaml:"namespace,omitempty"`

	// If specified, the port on the service that hosting webhook. Default to 443 for backward compatibility. `port` should be a valid port number (1-65535, inclusive).
	Port int32 `json:"port,omitempty" json,yaml:"port,omitempty"`
}

// Validate validates this io k8s kube aggregator pkg apis apiregistration v1beta1 service reference
func (m *IoK8sKubeAggregatorPkgApisApiregistrationV1beta1ServiceReference) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this io k8s kube aggregator pkg apis apiregistration v1beta1 service reference based on context it is used
func (m *IoK8sKubeAggregatorPkgApisApiregistrationV1beta1ServiceReference) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IoK8sKubeAggregatorPkgApisApiregistrationV1beta1ServiceReference) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoK8sKubeAggregatorPkgApisApiregistrationV1beta1ServiceReference) UnmarshalBinary(b []byte) error {
	var res IoK8sKubeAggregatorPkgApisApiregistrationV1beta1ServiceReference
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
