// Code generated by go-swagger; DO NOT EDIT.

package v1_20

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IoK8sAPIAuthorizationV1beta1NonResourceAttributes NonResourceAttributes includes the authorization attributes available for non-resource requests to the Authorizer interface
//
// swagger:model io.k8s.api.authorization.v1beta1.NonResourceAttributes
type IoK8sAPIAuthorizationV1beta1NonResourceAttributes struct {

	// Path is the URL path of the request
	Path string `json:"path,omitempty" json,yaml:"path,omitempty"`

	// Verb is the standard HTTP verb
	Verb string `json:"verb,omitempty" json,yaml:"verb,omitempty"`
}

// Validate validates this io k8s api authorization v1beta1 non resource attributes
func (m *IoK8sAPIAuthorizationV1beta1NonResourceAttributes) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this io k8s api authorization v1beta1 non resource attributes based on context it is used
func (m *IoK8sAPIAuthorizationV1beta1NonResourceAttributes) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IoK8sAPIAuthorizationV1beta1NonResourceAttributes) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoK8sAPIAuthorizationV1beta1NonResourceAttributes) UnmarshalBinary(b []byte) error {
	var res IoK8sAPIAuthorizationV1beta1NonResourceAttributes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
