// Code generated by go-swagger; DO NOT EDIT.

package v1_20

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IoK8sAPIAutoscalingV2beta1ContainerResourceMetricStatus ContainerResourceMetricStatus indicates the current value of a resource metric known to Kubernetes, as specified in requests and limits, describing a single container in each pod in the current scale target (e.g. CPU or memory).  Such metrics are built in to Kubernetes, and have special scaling options on top of those available to normal per-pod metrics using the "pods" source.
//
// swagger:model io.k8s.api.autoscaling.v2beta1.ContainerResourceMetricStatus
type IoK8sAPIAutoscalingV2beta1ContainerResourceMetricStatus struct {

	// container is the name of the container in the pods of the scaling target
	// Required: true
	Container *string `json:"container" json,yaml:"container"`

	// currentAverageUtilization is the current value of the average of the resource metric across all relevant pods, represented as a percentage of the requested value of the resource for the pods.  It will only be present if `targetAverageValue` was set in the corresponding metric specification.
	CurrentAverageUtilization int32 `json:"currentAverageUtilization,omitempty" json,yaml:"currentAverageUtilization,omitempty"`

	// currentAverageValue is the current value of the average of the resource metric across all relevant pods, as a raw value (instead of as a percentage of the request), similar to the "pods" metric source type. It will always be set, regardless of the corresponding metric specification.
	// Required: true
	CurrentAverageValue *IoK8sApimachineryPkgAPIResourceQuantity `json:"currentAverageValue" json,yaml:"currentAverageValue"`

	// name is the name of the resource in question.
	// Required: true
	Name *string `json:"name" json,yaml:"name"`
}

// Validate validates this io k8s api autoscaling v2beta1 container resource metric status
func (m *IoK8sAPIAutoscalingV2beta1ContainerResourceMetricStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContainer(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCurrentAverageValue(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoK8sAPIAutoscalingV2beta1ContainerResourceMetricStatus) validateContainer(formats strfmt.Registry) error {

	if err := validate.Required("container", "body", m.Container); err != nil {
		return err
	}

	return nil
}

func (m *IoK8sAPIAutoscalingV2beta1ContainerResourceMetricStatus) validateCurrentAverageValue(formats strfmt.Registry) error {

	if err := validate.Required("currentAverageValue", "body", m.CurrentAverageValue); err != nil {
		return err
	}

	if err := validate.Required("currentAverageValue", "body", m.CurrentAverageValue); err != nil {
		return err
	}

	if m.CurrentAverageValue != nil {
		if err := m.CurrentAverageValue.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("currentAverageValue")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("currentAverageValue")
			}
			return err
		}
	}

	return nil
}

func (m *IoK8sAPIAutoscalingV2beta1ContainerResourceMetricStatus) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this io k8s api autoscaling v2beta1 container resource metric status based on the context it is used
func (m *IoK8sAPIAutoscalingV2beta1ContainerResourceMetricStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCurrentAverageValue(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoK8sAPIAutoscalingV2beta1ContainerResourceMetricStatus) contextValidateCurrentAverageValue(ctx context.Context, formats strfmt.Registry) error {

	if m.CurrentAverageValue != nil {
		if err := m.CurrentAverageValue.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("currentAverageValue")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("currentAverageValue")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *IoK8sAPIAutoscalingV2beta1ContainerResourceMetricStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoK8sAPIAutoscalingV2beta1ContainerResourceMetricStatus) UnmarshalBinary(b []byte) error {
	var res IoK8sAPIAutoscalingV2beta1ContainerResourceMetricStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
