// Code generated by go-swagger; DO NOT EDIT.

package v1_20

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IoK8sAPICoreV1ComponentCondition Information about the condition of a component.
//
// swagger:model io.k8s.api.core.v1.ComponentCondition
type IoK8sAPICoreV1ComponentCondition struct {

	// Condition error code for a component. For example, a health check error code.
	Error string `json:"error,omitempty" json,yaml:"error,omitempty"`

	// Message about the condition for a component. For example, information about a health check.
	Message string `json:"message,omitempty" json,yaml:"message,omitempty"`

	// Status of the condition for a component. Valid values for "Healthy": "True", "False", or "Unknown".
	// Required: true
	Status *string `json:"status" json,yaml:"status"`

	// Type of condition for a component. Valid value: "Healthy"
	// Required: true
	Type *string `json:"type" json,yaml:"type"`
}

// Validate validates this io k8s api core v1 component condition
func (m *IoK8sAPICoreV1ComponentCondition) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoK8sAPICoreV1ComponentCondition) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

func (m *IoK8sAPICoreV1ComponentCondition) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this io k8s api core v1 component condition based on context it is used
func (m *IoK8sAPICoreV1ComponentCondition) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IoK8sAPICoreV1ComponentCondition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoK8sAPICoreV1ComponentCondition) UnmarshalBinary(b []byte) error {
	var res IoK8sAPICoreV1ComponentCondition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
