// Code generated by go-swagger; DO NOT EDIT.

package v1_20

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IoK8sApiextensionsApiserverPkgApisApiextensionsV1ServiceReference ServiceReference holds a reference to Service.legacy.k8s.io
//
// swagger:model io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.ServiceReference
type IoK8sApiextensionsApiserverPkgApisApiextensionsV1ServiceReference struct {

	// name is the name of the service. Required
	// Required: true
	Name *string `json:"name" json,yaml:"name"`

	// namespace is the namespace of the service. Required
	// Required: true
	Namespace *string `json:"namespace" json,yaml:"namespace"`

	// path is an optional URL path at which the webhook will be contacted.
	Path string `json:"path,omitempty" json,yaml:"path,omitempty"`

	// port is an optional service port at which the webhook will be contacted. `port` should be a valid port number (1-65535, inclusive). Defaults to 443 for backward compatibility.
	Port int32 `json:"port,omitempty" json,yaml:"port,omitempty"`
}

// Validate validates this io k8s apiextensions apiserver pkg apis apiextensions v1 service reference
func (m *IoK8sApiextensionsApiserverPkgApisApiextensionsV1ServiceReference) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNamespace(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoK8sApiextensionsApiserverPkgApisApiextensionsV1ServiceReference) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

func (m *IoK8sApiextensionsApiserverPkgApisApiextensionsV1ServiceReference) validateNamespace(formats strfmt.Registry) error {

	if err := validate.Required("namespace", "body", m.Namespace); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this io k8s apiextensions apiserver pkg apis apiextensions v1 service reference based on context it is used
func (m *IoK8sApiextensionsApiserverPkgApisApiextensionsV1ServiceReference) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IoK8sApiextensionsApiserverPkgApisApiextensionsV1ServiceReference) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoK8sApiextensionsApiserverPkgApisApiextensionsV1ServiceReference) UnmarshalBinary(b []byte) error {
	var res IoK8sApiextensionsApiserverPkgApisApiextensionsV1ServiceReference
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
