// Code generated by go-swagger; DO NOT EDIT.

package v1_20

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IoK8sAPIAutoscalingV2HPAScalingPolicy HPAScalingPolicy is a single policy which must hold true for a specified past interval.
//
// swagger:model io.k8s.api.autoscaling.v2.HPAScalingPolicy
type IoK8sAPIAutoscalingV2HPAScalingPolicy struct {

	// PeriodSeconds specifies the window of time for which the policy should hold true. PeriodSeconds must be greater than zero and less than or equal to 1800 (30 min).
	// Required: true
	PeriodSeconds *int32 `json:"periodSeconds"`

	// Type is used to specify the scaling policy.
	// Required: true
	Type *string `json:"type"`

	// Value contains the amount of change which is permitted by the policy. It must be greater than zero
	// Required: true
	Value *int32 `json:"value"`
}

// Validate validates this io k8s api autoscaling v2 h p a scaling policy
func (m *IoK8sAPIAutoscalingV2HPAScalingPolicy) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePeriodSeconds(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoK8sAPIAutoscalingV2HPAScalingPolicy) validatePeriodSeconds(formats strfmt.Registry) error {

	if err := validate.Required("periodSeconds", "body", m.PeriodSeconds); err != nil {
		return err
	}

	return nil
}

func (m *IoK8sAPIAutoscalingV2HPAScalingPolicy) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

func (m *IoK8sAPIAutoscalingV2HPAScalingPolicy) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this io k8s api autoscaling v2 h p a scaling policy based on context it is used
func (m *IoK8sAPIAutoscalingV2HPAScalingPolicy) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IoK8sAPIAutoscalingV2HPAScalingPolicy) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoK8sAPIAutoscalingV2HPAScalingPolicy) UnmarshalBinary(b []byte) error {
	var res IoK8sAPIAutoscalingV2HPAScalingPolicy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
