// Code generated by go-swagger; DO NOT EDIT.

package v1_20

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IoK8sAPICoreV1NamespaceSpec NamespaceSpec describes the attributes on a Namespace.
//
// swagger:model io.k8s.api.core.v1.NamespaceSpec
type IoK8sAPICoreV1NamespaceSpec struct {

	// Finalizers is an opaque list of values that must be empty to permanently remove object from storage. More info: https://kubernetes.io/docs/tasks/administer-cluster/namespaces/
	Finalizers []string `json:"finalizers"`
}

// Validate validates this io k8s api core v1 namespace spec
func (m *IoK8sAPICoreV1NamespaceSpec) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this io k8s api core v1 namespace spec based on context it is used
func (m *IoK8sAPICoreV1NamespaceSpec) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IoK8sAPICoreV1NamespaceSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoK8sAPICoreV1NamespaceSpec) UnmarshalBinary(b []byte) error {
	var res IoK8sAPICoreV1NamespaceSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
